In [1]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import sklearn.metrics as skm
import sklearn.preprocessing as skp
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, ParameterGrid
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.linear_model import LinearRegression, LogisticRegressionCV
from sklearn.naive_bayes import GaussianNB
from sklearn.impute import SimpleImputer
from sklearn import set_config
from bs4 import BeautifulSoup

import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', None)
set_config(display = 'diagram')

In [2]:
sheets = ['Denver Colorado', 
          'Los Angeles County California',
          'Jacksonville County Florida', 
          'Seattle County Washington', 
          'Tacoma Washington', 
          'Atlanta Georgia',
          'Bloomington Illinois',
          'Cincinnati Ohio',
          'Dallas Texas', 
          'Hampton',
          'Hartford Conneticut',
          'Indianapolis Indiana',
          'Orlando Florida',
          'Sparks Nevada',
          'Portland Oregon',
          'Louisville Kentucky',
          'Springfiled Missouri',
          'Charolette North Carolina 1',
          'Charolette North Carolina suspe',
          'Charolette North Carolina offic']

In [3]:
dictOfDfs = {}
for x in sheets:
    dictOfDfs[x] = pd.read_excel('officer_involved_shooting_all_info.xlsx', sheet_name=x)

In [4]:
# for key in dictOfDfs:
#     display(dictOfDfs[key].head())

In [5]:
finalColumns = [
    'city',
    'state',
    'id',
    'date',
    'time',
    'day_of_week',
    'incident_initiation',
    'officer_rank', 
    'suspect_sex',
    'suspect_age',
    'suspect_race',
    'suspect_ethnicity',
    'suspect_armed',
    'injury',
    'justified',
    'x_coord',
    'y_coord'
]

## General Mappings

In [176]:
race_map = {
    'White' : 'white',
    'WHITE' : 'white',
    'W' : 'white',
    'w' : 'white',
    'Black': 'black',
    'BLACK': 'black',
    'B' : 'black',
    'b' : 'black',
    'Hispanic': 'hispanic',
    'HISPANIC' : 'hispanic',
    'H' : 'hispanic',
    'h' : 'hispanic',
    'Unknown' : 'unknown',
    'UNK' : 'unknown',
    'UNKNOWN' : 'unknown'
}

sex_map = {
    'MALE': 'male',
    'Male' : 'male',
    'M' : 'male',
    'm' : 'male',
    'FEMALE' : 'female',
    'Female' : 'female',
    'F' : 'female',
    'f' : 'female'
}

## Denver

In [225]:
denver = dictOfDfs['Denver Colorado'].copy()

In [226]:
denver.columns = [
    'city', 
    'state', 
    'id', 
    'date', 
    'time', 
    'day_of_week', 
    'call_origination',
    'incident_initiation',
    'address', 
    'officer_first_last', 
    'role', 
    'officer_rank', 
    'officer_badge',  
    'officer_on_duty',
    'in_uniform', 
    'citizen_sex',
    'citizen_age',
    'citizen_race',
    'citizen_ethnicity',
    'citizen_armed',
    'citizen_shooting',
    'citizen_injury',
    'justified',
    'x_coord',
    'y_coord'
]

In [227]:
# for x in denver.columns:
#     display(denver[x].value_counts())

### Create categorical variable maps

In [228]:
suspect_armed_map = {
    'Firearm'                 : 'firearm',
    'Knife'                   : 'other',
    'None'                    :'unarmed',
    'Replica or Air Gun'      :'other',
    'Simulated Weapon'        :'unarmed',
    'Motor Vehicle'           :'other',
    'Blunt Object'            :'other',
    'Stun Gun'                :'other',
    'Shotgun'                 :'firearm'
}

In [229]:
incident_initiation_map = {
    'Weapon / Concealed Weapon'                 : 'weapon',                    
    'Warrant'                                   : 'warrant',                                    
    'Vehicle Stop'                              : 'traffic_stop',                                
    'Shots Fired'                               : 'shooting',                                  
    'Shooting'                                  : 'shooting',                                     
    'Street Robbery'                            : 'robbery',
    'Robbery - In Progress / Just Occurred'     : 'robbery'  ,       
    'Burglary - In Progess'                     : 'burglary',
    'Suspicious Vehicle'                        : 'suspicious_situation',                           
    'Surveillance'                              : 'police_surveillance' ,    
    'Domestic Violence - In Progress'           : 'dv'   ,           
    'Disturbance'                               : 'disturbance'  ,                                
    'Burglary - In Progress'                    : 'burglary' ,                      
    'Bank Robbery Suspect'                      : 'bolo',                         
    'Shots Heard/Fired'                         :'shooting'      ,                      
    'Suicidal Person / Suicide'                 : 'suicide' ,                   
    'Vehicle Check'                             : 'traffic_stop'  ,                              
    'Shot Spotter'                              : 'shooting'  ,                              
    'Robbery - Car Jacking '                    : 'robbery'  ,                      
    'Family Disturbance'                        : 'dv'   ,                        
    'Harassment in Progress Involving a Weapon' : 'weapon' ,
    'Burglary-In Progress'                      : 'burglary'     ,                    
    'Burglary/Suspicious Occurrence'            : 'burglary',
    'Man with a Gun'                            : 'weapon' ,                              
    'BOLO (Be on the lookout)'                  : 'bolo' ,                     
    'Business Robbery'                          : 'robbery'                             
}

In [230]:
denver['incident_initiation'] = denver['incident_initiation'].map(incident_initiation_map, na_action = 'ignore')
denver['citizen_armed'] = denver['citizen_armed'].map(suspect_armed_map, na_action = 'ignore')
denver['citizen_race'] = denver['citizen_race'].map(race_map)
denver['citizen_sex'] = denver['citizen_sex'].map(sex_map)

In [231]:
denver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   city                 127 non-null    object
 1   state                127 non-null    object
 2   id                   127 non-null    object
 3   date                 127 non-null    datetime64[ns]
 4   time                 127 non-null    int64
 5   day_of_week          127 non-null    object
 6   call_origination     127 non-null    object
 7   incident_initiation  125 non-null    object
 8   address              127 non-null    object
 9   officer_first_last   127 non-null    object
 10  role                 127 non-null    object
 11  officer_rank         78 non-null     object
 12  officer_badge        78 non-null     object
 13  officer_on_duty      78 non-null     object
 14  in_uniform           78 non-null     object
 15  citizen_sex          127 non-null    object
 16  citizen_age          127 non-null    int64
 17  citizen_race         124 non-null    object
 18  citizen_ethnicity    127 non-null    object
 19  citizen_armed        127 non-null    object
 20  citizen_shooting     123 non-null    object
 21  citizen_injury       127 non-null    object
 22  justified            127 non-null    object
 23  x_coord              127 non-null    object
 24  y_coord              127 non-null    object
dtypes: datetime64[ns](1), int64(2), object(22)
memory usage: 24.9+ KB

In [232]:
officers = pd.get_dummies(denver['officer_rank'])
suspects = pd.get_dummies(denver[['citizen_sex','citizen_race','citizen_ethnicity', 'citizen_armed']])
officerSuspectOneHot = pd.concat([denver['id'],officers,suspects],axis = 1)
dfDenver1 = officerSuspectOneHot.groupby(by = ['id'], axis = 0, dropna = False).sum()
dfDenver2 = denver.groupby(['id'], axis = 0, dropna = False).first()
denverEncoded = pd.merge(dfDenver2,dfDenver1, how = 'left', on = 'id').reset_index()
denverEncoded.head()
# dfDenver.drop(columns = [
#     'address', 
#     'officer_badge', 
#     'officer_on_duty', 
#     'in_uniform', 
#     'suspect_gender', 
#     'suspect_ethnicity', 
#     'suspect_armed',
#     'justified',
#     'role',
#     'officer_rank',
#     'suspect_race'
# ])

,id,city,state,date,time,day_of_week,call_origination,incident_initiation,address,officer_first_last,role,officer_rank,officer_badge,officer_on_duty,in_uniform,citizen_sex,citizen_age,citizen_race,citizen_ethnicity,citizen_armed,citizen_shooting,citizen_injury,justified,x_coord,y_coord,Corporal,Detective,Officer,Sergeant,Technician,citizen_sex_female,citizen_sex_male,citizen_race_black,citizen_race_white,citizen_ethnicity_H,citizen_ethnicity_NH,citizen_armed_firearm,citizen_armed_other,citizen_armed_unarmed
0,2020182,Denver,Colorado,2020-01-01,120,Wednesday,Citizen-Initiated,weapon,901 S Irving St,"Archuleta, Diego",Officer,Officer,P16061,On-Duty City Paid,Police Uniform,male,25,white,H,firearm,Yes,Not Injured,Investigation Pending,3132258,1680228,0,0,2,0,0,0,3,0,3,2,1,2,1,0
1,201516702,Denver,Colorado,2015-01-09,1940,Friday,Officer-Initiated,traffic_stop,5081 N Crown Blvd,"Kindell, Sharod",Subject,Officer,P08002,On-Duty City Paid,Police Uniform,male,24,black,NH,other,Yes,Injured,http://www.denverda.org/News_Release/Decision_...,3188620,1712709,0,0,1,0,0,0,2,1,1,0,2,1,1,0
2,201549266,Denver,Colorado,2015-01-26,700,Monday,Citizen-Initiated,suspicious_situation,2500 blk N Newport St / N Niagara St Alley,"Hernandez, Jessica",Subject,Officer,P05076,On-Duty City Paid,Police Uniform,female,17,white,H,other,Yes,Deceased,https://www.denverda.org/wp-content/uploads/de...,3165976,1700000,0,0,2,0,0,1,2,0,3,1,2,2,1,0
3,201621883,Denver,Colorado,2016-01-11,1529,Monday,Officer-Initiated,traffic_stop,2601 N Zuni St,"Lonergan, Ramone",Subject,Detective,P96014,On-Duty City Paid,Plain Clothes,male,32,white,NH,firearm,Yes,Deceased,https://www.denverda.org/wp-content/uploads/de...,3135850,1700412,0,1,1,0,0,0,3,0,3,1,2,3,0,0
4,201889020,Denver,Colorado,2018-02-06,1756,Tuesday,Citizen-Initiated,burglary,1873 S Alcott St,"Duran, Alexander",Subject,Corporal,P98027,On-Duty City Paid,Police Uniform,male,29,white,H,other,No,Deceased,https://www.denverda.org/wp-content/uploads/de...,3135881,1673982,1,0,0,0,0,0,2,0,2,1,1,1,1,0

## LA County

In [187]:
la_county = dictOfDfs['Los Angeles County California'].copy()
la_county.columns = [
    'id',
    'incident_initiation',
    'date',
    'address',
    'city',
    'state',
    'zip',
    'district',
    'geo_location',
    'unit_id',
    'unit_name',
    'num_officers_involved',
    'officer_race',
    'num_of_citizens',
    'citizen_race',
    'num_citizens_wounded',
    'num_citizens_killed',
    'citizen_armed',
    'citizen_armed_description',
    'x_coord',
    'y_coord'
]

In [188]:
la_county['citizen_race'] = la_county['citizen_race'].astype('str')

### Category Mappings to limit features

In [189]:
def func(x):
    if x in ['LOS ANGELES',                     
            'COMPTON'                  ,       
            'LANCASTER'                 ,      
            'PALMDALE'                   ,     
            'EAST LOS ANGELES'            ,    
            'PICO RIVERA'                  ,   
            'BELLFLOWER'                    ,   
            'LYNWOOD'                        ,  
            'NORWALK'                         , 
            'PARAMOUNT'                        ,
            'LAKEWOOD'                         ,
            'WHITTIER']:
        return x
    else:
        return 'other'

In [190]:
def func1(x):
    if x in [
        'CENTURY STN',                          
        'COMPTON STN',                          
        'EAST LA STN ',                         
        'LAKEWOOD STN' ,                        
        'SOUTH LOS ANGELES STATION',          
        'OPERATION SAFE STREETS BUREAU',      
        'PICO RIVERA STN'               ,       
        'INDUSTRY STN'                   ,      
        'LANCASTER STN'                   ,     
        'PALMDALE STN'                     ,    
        'SPECIAL ENFORCEMENT BUR'           ,   
        'TEMPLE CITY STN'                    ,  
        'SANTA CLARITA VALLEY STN'            , 
        'MAJOR CRIMES BUREAU'                  , 
        'CARSON STN'                            ,
        'NORWALK REGIONAL STN'                  ,
        'TRANSIT SERVICES BUREAU'               
    ]:
        return x
    else:
        return 'other'

In [191]:
weapon_map= {
    'A-1'   : 'firearm',
    'A-2'    :'firearm',
    'A-4'    :'unknown',
    'B-2'    : 'other',
    'B-1'    : 'other',
    'C-1'    : 'unarmed',
    'A-3'    : 'unknown',
    'D-1'    : 'unarmed',
    'B-4'    :  'unknown',
    'E-1'    :  'unarmed'
}

In [192]:
def get_specific_type(df, column, elementOfInterest,seperating_value = ','):
    def breakout_column(df,column,seperating_value):
        listOfDicts = []
        types = {}
        for x in df[column]:
            types[x] = types.get(x,0) + 1
        for x in df[column]:
            dictionary = {}
            broken_string = x.split(seperating_value)
            for y in broken_string:
                dictionary[y] = dictionary.get(y,0) + 1
            listOfDicts.append(dictionary)
        return listOfDicts
    breakoutColumn = breakout_column(df, column, seperating_value)
    return [x[elementOfInterest] if (elementOfInterest in list(x.keys())) else 0 for x in breakoutColumn]

### Officer encoding

In [193]:
la_county['city'] = la_county['city'].map(func, na_action = 'ignore')
la_county['unit'] = la_county['unit_name'].map(func1, na_action = 'ignore')
la_county['citizen_armed'] = la_county['citizen_race'].map(weapon_map, na_action = 'ignore')
la_county['citizen_armed_description'].map(weapon_map, na_action = 'ignore')
la_county['num_white_officers'] =  get_specific_type(la_county, 'officer_race', 'WHITE')
la_county['num_black_officers'] = get_specific_type(la_county, 'officer_race', 'BLACK')
la_county['num_hispanic_officers'] = get_specific_type(la_county, 'officer_race', 'HISPANIC')
la_county['num_filipino_officers'] = get_specific_type(la_county, 'officer_race', 'FILIPINO')
la_county['num_asian-pacific_officers'] = get_specific_type(la_county, 'officer_race', 'ASIAN-PACIFIC')
la_county['num_isl_officers'] = get_specific_type(la_county, 'officer_race', 'ISL')
la_county['num_asian-pacific-isl_officers'] = get_specific_type(la_county, 'officer_race', 'ASIAN-PACIFIC-ISL')
la_county['num_unknown_officers'] = get_specific_type(la_county, 'officer_race', 'UNKNOWN')

### Subject Encoding

In [194]:
la_county['num_white_persons'] = get_specific_type(la_county, 'citizen_race', 'WHITE')
la_county['num_black_persons'] = get_specific_type(la_county, 'citizen_race', 'BLACK')
la_county['num_hispanic_persons'] = get_specific_type(la_county, 'citizen_race', 'HISPANIC')
la_county['num_unknown_persons'] = get_specific_type(la_county, 'citizen_race', None)

In [195]:
la_county.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              360 non-null    int64
 1   incident_initiation             360 non-null    object
 2   date                            360 non-null    datetime64[ns]
 3   address                         360 non-null    object
 4   city                            356 non-null    object
 5   state                           360 non-null    object
 6   zip                             355 non-null    float64
 7   district                        358 non-null    float64
 8   geo_location                    360 non-null    object
 9   unit_id                         359 non-null    object
 10  unit_name                       359 non-null    object
 11  num_officers_involved           360 non-null    int64
 12  officer_race                    360 non-null    object
 13  num_of_citizens                 360 non-null    int64
 14  citizen_race                    360 non-null    object
 15  num_citizens_wounded            360 non-null    int64
 16  num_citizens_killed             360 non-null    int64
 17  citizen_armed                   0 non-null      object
 18  citizen_armed_description       354 non-null    object
 19  x_coord                         355 non-null    float64
 20  y_coord                         355 non-null    float64
 21  unit                            359 non-null    object
 22  num_white_officers              360 non-null    int64
 23  num_black_officers              360 non-null    int64
 24  num_hispanic_officers           360 non-null    int64
 25  num_filipino_officers           360 non-null    int64
 26  num_asian-pacific_officers      360 non-null    int64
 27  num_isl_officers                360 non-null    int64
 28  num_asian-pacific-isl_officers  360 non-null    int64
 29  num_unknown_officers            360 non-null    int64
 30  num_white_persons               360 non-null    int64
 31  num_black_persons               360 non-null    int64
 32  num_hispanic_persons            360 non-null    int64
 33  num_unknown_persons             360 non-null    int64
dtypes: datetime64[ns](1), float64(4), int64(17), object(12)
memory usage: 95.8+ KB

In [196]:
la_countyEncoded = la_county.copy()
la_countyEncoded.drop(columns = [
    'address',
    'zip',
    'geo_location',
    'unit_id',
    'officer_race',
    'num_of_citizens',
    'citizen_race',
    'citizen_armed_description',
    'unit'
])

,id,incident_initiation,date,city,state,district,unit_name,num_officers_involved,num_citizens_wounded,num_citizens_killed,citizen_armed,x_coord,y_coord,num_white_officers,num_black_officers,num_hispanic_officers,num_filipino_officers,num_asian-pacific_officers,num_isl_officers,num_asian-pacific-isl_officers,num_unknown_officers,num_white_persons,num_black_persons,num_hispanic_persons,num_unknown_persons
0,1000717,HIT SHOOTING INCIDENT,2016-03-30 15:25:00,other,CA,287.0,SPECIAL ENFORCEMENT BUR,1,0,1,NaN,34.012368,-118.126934,0,1,0,0,0,0,0,0,0,0,1,0
1,1000462,HIT SHOOTING INCIDENT,2013-10-06 15:30:00,LOS ANGELES,CA,6893.0,TRANSIT SERVICES BUREAU,1,0,1,NaN,34.006282,-118.428977,0,0,1,0,0,0,0,0,0,1,0,0
2,1000410,NON-HIT SHOOTING INCIDENT,2012-08-16 01:40:00,LOS ANGELES,CA,377.0,SOUTH LOS ANGELES STATION,1,0,0,NaN,33.917363,-118.300408,0,0,1,0,0,0,0,0,0,1,0,0
3,1001747,HIT SHOOTING INCIDENT,2019-08-02 09:29:00,other,CA,1361.0,LAKEWOOD STN,1,1,0,NaN,33.914619,-118.168995,1,0,0,0,0,0,0,0,0,0,0,0
4,1001627,NON-HIT SHOOTING INCIDENT,2018-11-25 16:03:00,other,CA,1127.0,LANCASTER STN,1,0,0,NaN,NaN,NaN,1,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,1000399,HIT SHOOTING INCIDENT,2012-05-05 23:37:00,PALMDALE,CA,1197.0,LANCASTER STN,2,1,0,NaN,34.601522,-117.832055,2,0,0,0,0,0,0,0,1,0,0,0
356,1000489,HIT SHOOTING INCIDENT,2014-06-24 21:51:00,COMPTON,CA,2824.0,COMPTON STN,2,1,1,NaN,33.898359,-118.209500,1,0,1,0,0,0,0,0,0,2,0,0
357,1000519,NON-HIT SHOOTING INCIDENT,2015-03-20 12:44:00,LOS ANGELES,CA,375.0,SOUTH LOS ANGELES STATION,1,0,0,NaN,33.940007,-118.291834,1,0,0,0,0,0,0,0,0,1,0,0
358,1000342,HIT SHOOTING INCIDENT,2011-02-26 03:53:00,LOS ANGELES,CA,283.0,EAST LA STN,1,1,0,NaN,34.033240,-118.169147,0,0,1,0,0,0,0,0,0,0,1,0
359,1000525,HIT SHOOTING INCIDENT,2015-05-13 17:41:00,COMPTON,CA,2824.0,COMPTON STN,1,1,0,NaN,33.896088,-118.207962,0,0,1,0,0,0,0,0,0,1,0,0

## Jacksonville

### Into exploration

In [197]:
jacksonville = dictOfDfs['Jacksonville County Florida'].copy()
jacksonville.head()

,IncidentDate,IncidentNbr,OriginalIncidentType,RTRCaseNbr,StreetNbr,StreetName,StreetType,StreetDirection,ApartmentNbr,City,StateProvince,PostalCode,Zone,SubSector,IncidentLocation,OfficerName,OfficerRace,OfficerGender,OfficerAge,OfficerTenure,SubjectName,SubjectRace,SubjectGender,SubjectAge,Subjectshot,Fatal,SubjectWeapon,UOFWithinPolicy,FurtherSituationalTrainingRequired,ReferredToIA,SAOLetterLinks,RTRCaseStatus
0,2020-07-26,2020-0479170,Traffic Violations,RTR20-0023,11500,San Jose,Blvd,NaN,NaN,Jacksonville,Florida,NaN,3.0,I3,"11500 San Jose Blvd\nJacksonville, Florida","Kampfe, Myers L.",W,M,25,1,"Paige, Darrell Lorenzo",B,M,21,Yes,No,Not Applicable (None),Pending,Pending,Pending,NaN,Pending State Attorney Review
1,2020-07-04,2020-0434871,Assault/Battery,RTR20-0022,4600,Monroe Smith,Rd,NaN,NaN,Jacksonville,Florida,NaN,4.0,L1,"4600 Monroe Smith Rd\nJacksonville, Florida","Gutcher, Robert O.",W,M,30,1,"Perez, Axal",W,M,17,Yes,Yes,Knife / Cutting Instr,Pending,Pending,Pending,NaN,Pending State Attorney Review
2,2020-07-03,2020-0431344,All Other,RTR20-0021,1100,Kendall,Dr,NaN,NaN,Jacksonville,Florida,NaN,2.0,D2,"1100 Kendall Dr\nJacksonville, Florida","Cross, Paul G.; Mccranie, Phillip L.",W; W,M; M,42; 44,10; 21,"Carter, Amante Tesean",B,M,28,No,No,Shotgun,Pending; Pending,Pending; Pending,Pending; Pending,NaN,Pending State Attorney Review
3,2020-07-01,2020-0428924,Auto Theft,RTR20-0020,5200,Soutel,Dr,NaN,NaN,Jacksonville,Florida,NaN,5.0,N3,"5200 Soutel Dr\nJacksonville, Florida","Mrakovich, Bryce M.",W,M,26,1,"Paul, Nalory Debaptiste",B,M,20,No,No,Not Applicable (None),Pending,Pending,Pending,NaN,Pending RTR Review Board Hearing
4,2020-05-26,2020-0351630,Traffic Violations,RTR20-0015,13400,J. Turner Butler,Blvd,NaN,NaN,Jacksonville,Florida,NaN,3.0,H1,"13400 J. Turner Butler Blvd\nJacksonville, Flo...","Ondriezek, Blaine J.",W,M,31,1,"Dunaway, John Allen",W,M,61,Yes,Yes,Personal Weapons (Hands/ Fist/ Feet/Teeth/Etc....,Pending,Pending,Pending,NaN,Pending RTR Review Board Hearing

In [198]:
jacksonville.info()
jacksonville.head()
jacksonville.columns = [
    'date',
    'id',
    'incident_initiation',
    'id2',
    'street_number',
    'street_name',
    'street_type',
    'street_direction',
    'apartment_number',
    'city',
    'state',
    'zip',
    'zone',
    'sub_zone',
    'incident_location',
    'officer_name',
    'officer_race',
    'officer_sex',
    'officer_age',
    'officer_year_of_services',
    'citizen_name',
    'citizen_race',
    'citizen_sex',
    'citizen_age',
    'citizen_injured',
    'citizen_killed',
    'citizen_armed',
    'UOFpolicy',
    'training?',
    'IA?',
    'SAO',
    'RTR'
]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   IncidentDate                        57 non-null     datetime64[ns]
 1   IncidentNbr                         57 non-null     object
 2   OriginalIncidentType                57 non-null     object
 3   RTRCaseNbr                          57 non-null     object
 4   StreetNbr                           57 non-null     int64
 5   StreetName                          57 non-null     object
 6   StreetType                          56 non-null     object
 7   StreetDirection                     13 non-null     object
 8   ApartmentNbr                        1 non-null      float64
 9   City                                57 non-null     object
 10  StateProvince                       57 non-null     object
 11  PostalCode                          26 non-null     float64
 12  Zone                                50 non-null     float64
 13  SubSector                           50 non-null     object
 14  IncidentLocation                    57 non-null     object
 15  OfficerName                         57 non-null     object
 16  OfficerRace                         57 non-null     object
 17  OfficerGender                       57 non-null     object
 18  OfficerAge                          57 non-null     object
 19  OfficerTenure                       57 non-null     object
 20  SubjectName                         57 non-null     object
 21  SubjectRace                         57 non-null     object
 22  SubjectGender                       57 non-null     object
 23  SubjectAge                          57 non-null     object
 24  Subjectshot                         57 non-null     object
 25  Fatal                               57 non-null     object
 26  SubjectWeapon                       55 non-null     object
 27  UOFWithinPolicy                     57 non-null     object
 28  FurtherSituationalTrainingRequired  57 non-null     object
 29  ReferredToIA                        57 non-null     object
 30  SAOLetterLinks                      0 non-null      float64
 31  RTRCaseStatus                       57 non-null     object
dtypes: datetime64[ns](1), float64(4), int64(1), object(26)
memory usage: 14.4+ KB

### Combining encoding for categorical variables with too many types.

In [199]:
original_incident_map = {
    'Traffic Violations'               : 'traffic_stop', 
    'All Other'                         :'other',
    'Robbery'                           :'robbery',
    'Assault/Battery'                   :'assault',
    'Armed Robbery'                     :'robbery',
    'Suspicious Person'                 :'suspicious_situation',
    'Traffic Stop'                      :'traffic_stop',
    'Narcotics Investigation'           :'police_surveillance',
    'Burglary'                          :'burglary',
    'Auto Theft'                        :'robbery',
    'Armed Dispute'                     :'weapon',
    'Person Shot'                       :'shooting',
    'Domestic Battery'                  :'dv',
    'Domestic Violence'                 :'dv',
    'Aggravated Battery'                :'assault',
    'Domestic'                          :'dv',
    'Intoxicated Person'                :'intoxication',
    'Suicide'                           :'suicide',
    'Armed Person'                      :'weapon',
    'Armed Prowler'                     :'weapon',
    'Suicide Threat / Armed Dispute'    :'suicide',
    'Murder'                            :'bolo',
    'Search Warrant'                    :'warrant',
    'Carjacking'                        :'robbery',
    'Shots fired'                       :'shooting',
    'Abduction/Kidnap'                  :'abduction',
    'Wanted Person'                     :'bolo',
    'Bomb Investigation'                :'police_surveillance'
}

In [200]:
subject_weapon_map = {
    'Handgun'                                :'firearm',
    'Knife / Cutting Instr'                  :'melee',
    'Vehicle'                                :'other',
    'Rifle'                                  :'firearm',
    'Shotgun'                                :'firearm',
    'Not Applicable (None)'                  :'None',
    'Firearm (Type Not Stated)'              :'firearm',
    'Taser'                                  :'other',
    'Knife / Cutting Instr; Poison (Includes Gas)' : 'melee',
    'Replica Handgun'                        :'other',
    'Knife'                                  :'melee',
    'Personal Weapons (Hands/ Fist/ Feet/Teeth/Etc.); Simulated Weapon' : 'None',
    'Sword'                                  :'melee',
    'BB Pistol'                              :'other',
    'None'                                   :'None'
}

In [201]:
jacksonville['citizen_armed'] = jacksonville['citizen_armed'].map(subject_weapon_map)
jacksonville['incident_initiation'] = jacksonville['incident_initiation'].map(original_incident_map)

In [202]:
def split_num_string(column):
    temp = []
    for x in column:
        try:
            thing = x.split('; ')
            newTemp = []
            for y in thing:
                newTemp.append(int(y))
            temp.append(newTemp)
        except:
            temp.append(x)
    return temp

def check_int_or_list(element):
    temp = []
    for x in element:
        try:
            temp.append(sum(x)/len(x))
        except:
            temp.append(x)
    return temp

### Encoding poorly formatted string data

#### Officer columns

In [32]:
jacksonville['officer_age'] = split_num_string(jacksonville['officer_age']) 
jacksonville['officer_year_of_services'] = split_num_string(jacksonville['officer_year_of_services'])
jacksonville['num_white_officers'] =  get_specific_type(jacksonville, 'officer_race', 'W', seperating_value='; ')
jacksonville['num_black_officers'] = get_specific_type(jacksonville, 'officer_race', 'B', seperating_value='; ')
jacksonville['num_hispanic_officers'] = get_specific_type(jacksonville, 'officer_race', 'H', seperating_value='; ')
jacksonville['num_asian_officers'] = get_specific_type(jacksonville, 'officer_race', 'A', seperating_value='; ')
jacksonville['average_officer_age'] = check_int_or_list(jacksonville['officer_race'])
jacksonville['average_officer_tenure'] = check_int_or_list(jacksonville['officer_year_of_services'])

#### Subject Columns

In [33]:
jacksonville['citizen_age'] = split_num_string(jacksonville['citizen_age']) 
jacksonville['num_white_citizens'] =  get_specific_type(jacksonville, 'citizen_race', 'W', seperating_value='; ')
jacksonville['num_black_citizens'] = get_specific_type(jacksonville, 'citizen_race', 'B', seperating_value='; ')
jacksonville['num_hispanic_citizens'] = get_specific_type(jacksonville, 'citizen_race', 'H', seperating_value='; ')
jacksonville['num_asian_citizens'] = get_specific_type(jacksonville, 'citizen_race', 'A', seperating_value='; ')
jacksonville['average_citizen_age'] = check_int_or_list(jacksonville['citizen_age'])

In [34]:
jacksonville.incident_initiation.value_counts()

traffic_stop            11
robbery                 10
other                    7
assault                  5
police_surveillance      4
weapon                   3
suspicious_situation     3
dv                       3
bolo                     2
burglary                 2
suicide                  2
shooting                 2
abduction                1
intoxication             1
warrant                  1
Name: incident_initiation, dtype: int64

In [35]:
# jacksonville['OriginalIncidentType'] = jacksonville['OriginalIncidentType'].map(original_incident_map, na_action = 'ignore')
# jacksonville.OriginalIncidentType.value_counts()

In [36]:
jacksonville['citizen_armed'].value_counts()

firearm    33
melee      11
other       7
None        4
Name: citizen_armed, dtype: int64

In [37]:
jacksonvilleEncoded  = jacksonville.copy()
jacksonvilleEncoded.drop(columns = [
    'date',
    'id',
    'id2',
    'incident_initiation',
    'street_number',
    'street_name',
    'street_type',
    'street_direction',
    'apartment_number',
    'officer_name',
    'UOFpolicy',
    'training?',
    'IA?',
    'SAO',
    'RTR'
])

,city,state,zip,zone,sub_zone,incident_location,officer_race,officer_sex,officer_age,officer_year_of_services,citizen_name,citizen_race,citizen_sex,citizen_age,citizen_injured,citizen_killed,citizen_armed,num_white_officers,num_black_officers,num_hispanic_officers,num_asian_officers,average_officer_age,average_officer_tenure,num_white_citizens,num_black_citizens,num_hispanic_citizens,num_asian_citizens,average_citizen_age
0,Jacksonville,Florida,NaN,3.0,I3,"11500 San Jose Blvd\nJacksonville, Florida",W,M,25,1,"Paige, Darrell Lorenzo",B,M,21,Yes,No,None,1,0,0,0,W,1.0,0,1,0,0,21
1,Jacksonville,Florida,NaN,4.0,L1,"4600 Monroe Smith Rd\nJacksonville, Florida",W,M,30,1,"Perez, Axal",W,M,17,Yes,Yes,melee,1,0,0,0,W,1.0,1,0,0,0,17
2,Jacksonville,Florida,NaN,2.0,D2,"1100 Kendall Dr\nJacksonville, Florida",W; W,M; M,"[42, 44]","[10, 21]","Carter, Amante Tesean",B,M,28,No,No,firearm,2,0,0,0,W; W,15.5,0,1,0,0,28
3,Jacksonville,Florida,NaN,5.0,N3,"5200 Soutel Dr\nJacksonville, Florida",W,M,26,1,"Paul, Nalory Debaptiste",B,M,20,No,No,None,1,0,0,0,W,1.0,0,1,0,0,20
4,Jacksonville,Florida,NaN,3.0,H1,"13400 J. Turner Butler Blvd\nJacksonville, Flo...",W,M,31,1,"Dunaway, John Allen",W,M,61,Yes,Yes,None,1,0,0,0,W,1.0,1,0,0,0,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,Jacksonville,Florida,32218.0,6.0,P1,"11050 Harts Rd\nJacksonville, Florida",W,M,28,2,"Kimbrough, Edward",B,M,14,Yes,No,other,1,0,0,0,W,2.0,0,1,0,0,14
53,Jacksonville,Florida,32211.0,2.0,E2,"212 Century St\nJacksonville, Florida",W,M,36,9,"Graham, Jerry",B,M,34,Yes,Yes,firearm,1,0,0,0,W,9.0,0,1,0,0,34
54,Jacksonville,Florida,32220.0,5.0,O2,"9452 Old Plank Rd\nJacksonville, Florida",W; W,M; M,"[43, 46]","[18, 22]","Compo, Richard",W,M,37,Yes,Yes,firearm,2,0,0,0,W; W,20.0,1,0,0,0,37
55,Baldwin,Florida,32234.0,5.0,O2,"100 Delmonte St\nBaldwin, Florida",W,M,54,12,"Brooks, Robert",B,M,26,No,No,None,1,0,0,0,W,12.0,0,1,0,0,26
56,Jacksonville,Florida,32207.0,3.0,G1,"3605 Drexel St\nJacksonville, Florida",W,M,35,9,"Larosa, Victo",B,M,23,Yes,Yes,other,1,0,0,0,W,9.0,0,1,0,0,23

## Seattle Washington

### Intro Exploration

In [44]:
seattle = dictOfDfs['Seattle County Washington'].copy()
seattle.info()
seattle.columns = [
    'thing1',
    'id',
    'date/time',
    'address',
    'y_coord',
    'x_coord',
    'city',
    'state',
    'officer_rank',
    'officer_sex',
    'officer_race',
    'officer_year_of_service',
    'officer_injured',
    'num_of_rounds',
    'citizen_sex',
    'citizen_race',
    'citizen_DOB',
    'citizen_age',
    'citizen_armed',
    'citizen_weapon',
    'citizen_killed',
    'on_duty',
    'disposition',
    'officer_disciplined',
    'summary'
] 
seattle.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FRB #                 75 non-null     object
 1   Incident Number       156 non-null    int64
 2   Date / Time           156 non-null    datetime64[ns]
 3   Blurred Address       156 non-null    object
 4   Longitude             156 non-null    float64
 5   Latitude              156 non-null    float64
 6   City                  156 non-null    object
 7   State                 156 non-null    object
 8   Rank                  156 non-null    object
 9   Officer Gender        156 non-null    object
 10  Officer Race          156 non-null    object
 11  Years of SPD Service  154 non-null    object
 12  Officer Injured       145 non-null    object
 13  Number of Rounds      156 non-null    object
 14  Subject Gender        156 non-null    object
 15  Subject Race          156 non-null    object
 16  Subject DOB           153 non-null    object
 17  Subject Age           154 non-null    object
 18  Subject Weapon        156 non-null    object
 19  Type of Weapon        129 non-null    object
 20  Fatal                 156 non-null    object
 21  On-duty               156 non-null    object
 22  Disposition           156 non-null    object
 23  Officer Disciplined?  155 non-null    object
 24  Summary               156 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(21)
memory usage: 30.6+ KB

,thing1,id,date/time,address,y_coord,x_coord,city,state,officer_rank,officer_sex,officer_race,officer_year_of_service,officer_injured,num_of_rounds,citizen_sex,citizen_race,citizen_DOB,citizen_age,citizen_armed,citizen_weapon,citizen_killed,on_duty,disposition,officer_disciplined,summary
0,FRB 05-01,20050000118193,2005-03-21 18:28:00,65XX BLOCK OF RAINIER AV S,-122.273741,47.543815,Seattle,WA,Officer,Male,White,20,No,1,Male,Asian,1975-11-03T00:00:00.000,29,Yes,Knife,Yes,Yes,Missing,Missing,"On March 21st, 2005, at approximately 5:20 P.M..."
1,FRB 05-03,20050000174022,2005-04-29 03:30:00,65XX BLOCK OF 1 AV S,-122.334513,47.544177,Seattle,WA,Officer,Male,White,5,No,2,Male,White,1969-08-02T00:00:00.000,36,No,NaN,Yes,Yes,Justified,No,"On April 29th, 2005, at approximately 3:35 A.M..."
2,FRB 05-04,20050000256303,2005-06-20 11:30:00,7XX BLOCK OF STEWART ST,-122.335725,47.614620,Seattle,WA,Officer,Male,White,15,No,1,Male,White,1952-11-15T00:00:00.000,53,Yes,"Grenade, backpack reported to have explosives",Yes,Yes,Justified,No,"On June 20th, 2005, at approximately 11:30 A.M..."
3,FRB 05-04,20050000256303,2005-06-20 12:30:00,7XX BLOCK OF STEWART ST,-122.335725,47.614620,Seattle,WA,Officer,Male,White,18,No,1,Male,White,1952-11-15T00:00:00.000,53,Yes,"Grenade, backpack reported to have explosives",Yes,Yes,Justified,No,"On June 20th, 2005, at approximately 11:30 A.M..."
4,FRB 05-05,20050000286240,2005-07-08 13:48:00,16 AV / E UNION ST,-122.311474,47.612908,Seattle,WA,Officer,Male,White,4,Yes,1,Male,Black or African American,1957-01-28T00:00:00.000,48,Yes,Screwdriver,No,Yes,Justified,No,"On July 8th, 2005, at approximately 1:45 P.M.,..."

### Collapsing string categories

In [45]:
type_of_weapon_map = {
    'Handgun'                                       :'firearm',
    'Knife'                                         :'melee',
    'Gun'                                           :'firearm',
    'Vehicle'                                       :'other',
    'Multiple Types'                                :'other',
    'Multiple Firearms'                             :'firearm',
    'Rifle'                                         :'firearm',
    'Metal Bar'                                     :'melee',
    'Grenade, backpack reported to have explosives' :'explosive',
    '.22 caliber pistol'                            :'firearm',
    'Colt Revolver'                                 :'firearm',
    '6 shot .357 revolver'                          :'firearm',
    'Rifle w/ bayonet'                              :'firearm',
    'broken bottle'                                 :'melee',
    'Board'                                         :'melee',
    'Screwdriver'                                   :'melee',
    '9mm semi-automatic'                            :'firearm',
    'Air soft rifle'                                :'other',
    '.357 revolver'                                 :'firearm',
    'Semil automatic .38 caliber handgun'           :'firearm',
    'Mac-10, 9 mm machine pistol'                   :'firearm'
}

In [46]:
rank_map = {
    'Officer'                  :'officer',
    'POLICE OFFICE'            :'officer',
    'Sergeant'                 :'sergeant',
    'Detective'                :'detective',
    'POLICE OFFIVER PROBATION' :'officer',
    'Student Officer'          :'student_officer',
    'POLICE OFFICER DETECTIVE' :'detective',
    'POLICE LIEUTENANT'        :'lieutenant',
    'FTO'                      :'officer',
    'POLICE SERGEANT'          :'sergeant'
}

In [47]:
subject_race_map = {
    'White'                        :'white',
    'Black or African American'    :'black',
    'Asian'                        :'asian',
    'Native American'              :'native_american',
    'Not Specified'                :'unknown',
    'Hispanic'                     :'hispanic',
    'Nat Hawaiian/Oth Pac Islander':'islander'
}

In [48]:
officer_race_map = {
    'White'                        :'white',
    'AI/AN'                        :'native_american',
    'Black or African American '   :'black',
    'Hispanic/Lation'              :'latino',
    'Asian/Pacific Islander'       :'pacific-islander',
    'Black'                        :'black',
    'Hispanic or Latino'           :'latino',
    'Multi-Racial'                 :'multi-racial',
    'Asian'                        :'asian',
    'American Indian/Alaska Native':'native_american',
    'Two or More Races'            :'multi-racial',
    'Nat Hawaiian/Oth Pac Islander':'pacific-islander',
}

In [49]:
seattle['citizen_weapon'] = seattle['citizen_weapon'].map(type_of_weapon_map)
seattle['officer_rank'] = seattle['officer_rank'].map(rank_map)
seattle['officer_race'] = seattle['officer_race'].map(officer_race_map)
seattle['citizen_race'] = seattle['citizen_race'].map(subject_race_map)

In [53]:
seattle.drop(columns = [
    'thing1',
    'citizen_DOB',
    'address',

   
    'num_of_rounds',
   
    'on_duty',
    'disposition',
    'officer_disciplined',
    'summary'
]).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       156 non-null    int64
 1   date/time                156 non-null    datetime64[ns]
 2   y_coord                  156 non-null    float64
 3   x_coord                  156 non-null    float64
 4   city                     156 non-null    object
 5   state                    156 non-null    object
 6   officer_rank             96 non-null     object
 7   officer_sex              156 non-null    object
 8   officer_race             147 non-null    object
 9   officer_year_of_service  154 non-null    object
 10  officer_injured          145 non-null    object
 11  citizen_sex              156 non-null    object
 12  citizen_race             156 non-null    object
 13  citizen_age              154 non-null    object
 14  citizen_armed            156 non-null    object
 15  citizen_weapon           125 non-null    object
 16  citizen_killed           156 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(13)
memory usage: 20.8+ KB

### Encoding Officer and Subject Information

In [54]:
officers = pd.get_dummies(seattle[
     [
         'id',
         'officer_rank', 
         'officer_sex', 
         'officer_race',  
         'officer_injured',
         'officer_disciplined'
     ]
])
subjects = pd.get_dummies(seattle[
    [
        'citizen_sex',
        'citizen_race',
        'citizen_weapon'
    ]
])
officersSubjects = pd.concat([ officers, subjects], axis = 1)
seattleEncoded = pd.concat([seattle.groupby(['id']).first(), officersSubjects.groupby(['id']).sum()], 
                           axis = 1).reset_index()
seattleEncoded

,id,thing1,date/time,address,y_coord,x_coord,city,state,officer_rank,officer_sex,officer_race,officer_year_of_service,officer_injured,num_of_rounds,citizen_sex,citizen_race,citizen_DOB,citizen_age,citizen_armed,citizen_weapon,citizen_killed,on_duty,disposition,officer_disciplined,summary,officer_rank_detective,officer_rank_lieutenant,officer_rank_officer,officer_rank_sergeant,officer_rank_student_officer,officer_sex_Female,officer_sex_Male,officer_race_asian,officer_race_black,officer_race_latino,officer_race_multi-racial,officer_race_native_american,officer_race_pacific-islander,officer_race_white,officer_injured_No,officer_injured_Yes,officer_disciplined_Missing,officer_disciplined_No,officer_disciplined_Yes,citizen_sex_Female,citizen_sex_Male,citizen_race_asian,citizen_race_black,citizen_race_hispanic,citizen_race_islander,citizen_race_native_american,citizen_race_unknown,citizen_race_white,citizen_weapon_explosive,citizen_weapon_firearm,citizen_weapon_melee,citizen_weapon_other
0,20050000118193,FRB 05-01,2005-03-21 18:28:00,65XX BLOCK OF RAINIER AV S,-122.273741,47.543815,Seattle,WA,officer,Male,white,20,No,1,Male,asian,1975-11-03T00:00:00.000,29,Yes,melee,Yes,Yes,Missing,Missing,"On March 21st, 2005, at approximately 5:20 P.M...",0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0
1,20050000174022,FRB 05-03,2005-04-29 03:30:00,65XX BLOCK OF 1 AV S,-122.334513,47.544177,Seattle,WA,officer,Male,white,5,No,2,Male,white,1969-08-02T00:00:00.000,36,No,NaN,Yes,Yes,Justified,No,"On April 29th, 2005, at approximately 3:35 A.M...",0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
2,20050000256303,FRB 05-04,2005-06-20 11:30:00,7XX BLOCK OF STEWART ST,-122.335725,47.614620,Seattle,WA,officer,Male,white,15,No,1,Male,white,1952-11-15T00:00:00.000,53,Yes,explosive,Yes,Yes,Justified,No,"On June 20th, 2005, at approximately 11:30 A.M...",0,0,2,0,0,0,2,0,0,0,0,0,0,2,2,0,0,2,0,0,2,0,0,0,0,0,0,2,2,0,0,0
3,20050000286240,FRB 05-05,2005-07-08 13:48:00,16 AV / E UNION ST,-122.311474,47.612908,Seattle,WA,officer,Male,white,4,Yes,1,Male,black,1957-01-28T00:00:00.000,48,Yes,melee,No,Yes,Justified,No,"On July 8th, 2005, at approximately 1:45 P.M.,...",0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0
4,20050000388203,FRB 05-06,2005-09-10 03:45:00,3XX BLOCK OF 9 AV,-122.323444,47.604128,Seattle,WA,officer,Male,white,5,No,1,Female,white,1962-02-18T00:00:00.000,44,No,NaN,No,Yes,Not Justified,Yes,"On September 10th, 2005, at approximately 3:45...",0,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,20190000048393,NaN,2019-02-07 03:22:00,105XX BLOCK MIDVALE AV N,-122.343340,47.705960,Seattle,WA,NaN,Male,white,17,NaN,3,Male,unknown,1900-01-01T00:00:00.000,117,Yes,melee,Yes,Yes,Within Policy,No,"On the 7th of February 2019, at 3:22 A.M., the...",0,0,0,0,0,0,2,0,0,0,0,0,0,1,0,0,0,2,0,0,2,0,0,0,0,0,2,0,0,0,2,0
73,20190000098802,NaN,2019-03-19 21:20:00,1600 BLOCK MELROSE AV,-122.327899,47.615472,Seattle,WA,NaN,Male,white,3,NaN,Multiple,Male,asian,1982-02-28T00:00:00.000,37,Yes,firearm,No,Yes,Within Policy,No,"On the 19th of March 2019, at 9:21 P.M., Settl...",0,0,0,0,0,0,4,0,0,0,0,0,0,4,0,0,0,4,0,0,4,4,0,0,0,0,0,0,0,4,0,0
74,20190000160099,NaN,2019-05-05 02:07:00,OCCIDENTAL AV / YESLER WY,-122.332874,47.601721,Seattle,WA,NaN,Male,white,6,NaN,2,Male,black,1900-01-01T00:00:00.000,118,Yes,firearm,No,Yes,Within Policy,No,"On the 5th of May 2019, at approximately 2:05 ...",0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0
75,20190000165328,NaN,2019-05-08 19:24:00,600 BLOCK 3 AV W,-122.360624,47.625198,Seattle,WA,NaN,Male,multi-racial,5,NaN,2,Male,unknown,1900-01-01T00:00:00.000,118,Yes,melee,Yes,Yes,Within Policy,No,"On the 8th of May 2019, at approximately 7:15 ...",0,0,0,0,0,0,2,0,0,0,1,0,0,1,0,0,0,2,0,0,2,0,0,0,0,0,2,0,0,0,2,0
76,20190000243418,NaN,2019-07-03 20:11:00,1000 BLOCK S JACKSON ST,-122.318431,47.599187,Seattle,WA,NaN,Male,white,6,NaN,Multiple,Female,asian,1987-02-28T00:00:00.000,32,Yes,firearm,No,Yes,Within Policy,No,"On the 3rd of July 2019, the Seattle Police Co...",0,0,0,0,0,0,2,0,0,0,0,0,0,2,0,0,0,2,0,2,0,2,0,0,0,0,0,0,0,2,0,0

In [ ]:
# seattle.drop(columns = ['FRB #', 'Incident Number','Blurred Address','Subject DOB','On-duty',
#        'Disposition', 'Officer Disciplined?', 'Summary'])

## Tacoma Washington

### Intro Exploration

In [114]:
tacoma = dictOfDfs['Tacoma Washington'].copy()
tacoma.columns = [
    'city',
    'state',
    'IA',
    'id',
    'address',
    'district',
    'sector',
    'date',
    'date2',
    'day_of_week',
    'time',
    'hour',
    'Inside/Outside',
    'officer_race',
    'officer_sex',
    'officer_age',
    'officer_years_of_service',
    'citizen_race', 
    'citizen_sex',
    'citizen_age',
    'Dipisition',
    'Action_Taken'
]
tacoma = tacoma.drop(columns = [
    'IA',
    'date2',
    'hour',
    'Inside/Outside',
   
    'Dipisition',
    'Action_Taken'
])
tacoma.info()
tacoma.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   city                      36 non-null     object
 1   state                     36 non-null     object
 2   id                        36 non-null     int64
 3   address                   36 non-null     object
 4   district                  35 non-null     object
 5   sector                    35 non-null     float64
 6   date                      36 non-null     datetime64[ns]
 7   day_of_week               36 non-null     object
 8   time                      36 non-null     object
 9   officer_race              36 non-null     object
 10  officer_sex               36 non-null     object
 11  officer_age               36 non-null     int64
 12  officer_years_of_service  34 non-null     float64
 13  citizen_race              36 non-null     object
 14  citizen_sex               36 non-null     object
 15  citizen_age               36 non-null     int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(10)
memory usage: 4.6+ KB

,city,state,id,address,district,sector,date,day_of_week,time,officer_race,officer_sex,officer_age,officer_years_of_service,citizen_race,citizen_sex,citizen_age
0,Tacoma,Washington,1918302031,"3840 Pacific Ave\nTacoma, WA\n(47.221717, -122...",TA43,4.0,2019-07-03,Tues,1899-12-31T21:01:00.000,White,Male,23,1.0,Asian,Female,56
1,Tacoma,Washington,1920200728,"500 S 40th St\nTacoma, WA\n(47.220858, -122.43...",TA43,4.0,2019-07-21,Sun,1899-12-31T10:46:00.000,White,Male,39,10.0,Black,Male,28
2,Tacoma,Washington,1919400316,"1623 E J St\nTacoma, WA\n(47.249159, -122.422549)",TA14,1.0,2019-07-16,Sat,1899-12-31T04:05:00.000,White,Male,45,20.0,White,Male,69
3,Tacoma,Washington,1925100213,"3400 E Portland Ave\nTacoma, WA\n(47.23279, -1...",TA41,4.0,2019-09-24,Sun,1899-12-31T02:36:00.000,White,Male,33,4.0,Black,Male,24
4,Tacoma,Washington,1919400316,"1623 E J St\nTacoma, WA\n(47.249159, -122.422549)",TA14,1.0,2019-07-16,Sat,1899-12-31T04:05:00.000,White,Male,28,0.0,White,Male,69

In [115]:
for columns in tacoma.columns:
    print(tacoma[columns].value_counts())

Tacoma    36
Name: city, dtype: int64
Washington    36
Name: state, dtype: int64
1800701780    7
1633501301    4
1919400316    4
1725301029    3
1730901676    2
130581374     1
1621901280    1
152171144     1
133290122     1
1918302031    1
1920200728    1
122821213     1
1600300777    1
151420459     1
1602801965    1
122440754     1
131800756     1
1925100213    1
151301177     1
140571388     1
123571013     1
Name: id, dtype: int64
425 S 59th St\nTacoma, Washington\n(47.203686, -122.437797)           7
1623 E J St\nTacoma, WA\n(47.249159, -122.422549)                     4
413 E 52nd St\nTacoma, Washington\n(47.209948, -122.42594)            4
5620 S Lawrence St\nTacoma, Washington\n(47.205388, -122.479098)      3
300 S 84th St\nTacoma, Washington\n(47.18097, -122.435594)            2
2800 Portland Ave\nTacoma, Washington\n(47.2388, -122.41045)          1
3228 S Union Ave\nTacoma, Washington\n(47.230454, -122.48364)         1
600 E 82nd St\nTacoma, Washington\n(47.18272, -122.423571)            1
809 S M St\nTacoma, Washington\n(47.254333, -122.455172)              1
3529 McKinley Ave\nTacoma, Washington\n(47.229192, -122.420712)       1
1400 S J St\nTacoma, Washington\n(47.249073, -122.449621)             1
3840 Pacific Ave\nTacoma, WA\n(47.221717, -122.434025)                1
2300 21st St SW\nPuyallup, Washington\n(47.169799, -122.320296)       1
3420 S Proctor St\nTacoma, Washington\n(47.22854, -122.488479)        1
5600 S Washington St\nTacoma, Washington\n(47.206173, -122.485053)    1
400 N Tacoma Ave\nTacoma, Washington\n(47.265955, -122.452613)        1
1658 S 47th St\nTacoma, Washington\n(47.214676, -122.456839)          1
3400 E Portland Ave\nTacoma, WA\n(47.23279, -122.409081)              1
3567 S Fawcett Ave\nTacoma, Washington\n(47.227743, -122.437576)      1
500 S 40th St\nTacoma, WA\n(47.220858, -122.437509)                   1
3318 S Sawyer St\nTacoma, Washington                                  1
Name: address, dtype: int64
TA43    14
TA14     4
TA41     3
TA44     3
TA33     3
TA32     3
TA12     2
TA31     2
TA21     1
Name: district, dtype: int64
4.0    20
3.0     8
1.0     6
2.0     1
Name: sector, dtype: int64
2018-01-07    7
2019-07-16    4
2016-12-02    4
2017-09-10    3
2017-11-05    2
2016-01-03    1
2012-12-24    1
2016-01-29    1
2019-07-03    1
2012-10-09    1
2015-05-26    1
2013-11-25    1
2013-06-29    1
2019-09-24    1
2014-02-27    1
2016-08-06    1
2015-08-05    1
2015-05-10    1
2013-02-27    1
2012-08-31    1
2019-07-21    1
Name: date, dtype: int64
Sun     16
Sat      7
Fri      5
Wed      4
Mon      2
Thur     1
Tues     1
Name: day_of_week, dtype: int64
22:47:00                   7
1899-12-31T04:05:00.000    4
19:26:00                   3
14:40:00                   3
21:30:00                   2
21:11:00                   1
13:52:00                   1
21:49:00                   1
1899-12-31T02:36:00.000    1
15:40:00                   1
17:34:00                   1
15:59:00                   1
15:05:00                   1
22:41:00                   1
18:38:00                   1
1899-12-31T10:46:00.000    1
1899-12-31T21:01:00.000    1
10:39:00                   1
22:08:00                   1
21:41:00                   1
03:05:00                   1
23:45:00                   1
Name: time, dtype: int64
White       30
Asian        3
Black        2
Hispanic     1
Name: officer_race, dtype: int64
Male      33
Female     3
Name: officer_sex, dtype: int64
35    4
33    2
48    2
28    2
42    2
40    2
38    2
34    2
61    1
23    1
24    1
25    1
27    1
29    1
30    1
32    1
36    1
59    1
39    1
44    1
45    1
47    1
50    1
52    1
56    1
22    1
Name: officer_age, dtype: int64
6.0     3
7.0     3
0.0     3
2.0     3
10.0    2
4.0     2
25.0    2
11.0    2
1.0     2
24.0    1
14.0    1
21.0    1
13.0    1
9.0     1
3.0     1
18.0    1
22.0    1
5.0     1
20.0    1
23.0    1
12.0    1
Name: officer_years_of_service, dtype: int64
Male           17
White          10
Black           5
Nat Am          1
Hispanic        1
Native Amer     1
Asian           1
Name: citizen_race, dtype: int64
Male        16
White       12
Black        4
Female       3
Hispanic     1
Name: citizen_sex, dtype: int64
27    7
69    4
38    4
58    3
33    2
28    2
40    1
45    1
35    1
34    1
32    1
56    1
29    1
48    1
26    1
25    1
24    1
23    1
22    1
30    1
Name: citizen_age, dtype: int64

### Fixing Data Switching between columns

In [116]:
def the_switchero(df, column1):
    newColumn1 = []
    for x in df[column1]:
        if (x == 'Male') | (x == 'Female'):
            newColumn1.append(1)
        else:
            newColumn1.append(0)
    df['bad_gender'] = newColumn1
    corrected_gender = []
    corrected_race = []
    for z,k in df.iterrows():
        if k['bad_gender'] == 1:
            corrected_gender.append(k['citizen_race'])
            corrected_race.append(k['citizen_sex'])
        else:
            corrected_gender.append(k['citizen_sex'])
            corrected_race.append(k['citizen_race'])
    return corrected_gender,corrected_race

In [120]:
tacoma['corrected_citizen_sex'], tacoma['corrected_citizen_race'] = the_switchero(tacoma, 'citizen_race')

### Officer and Citizen Encoding

In [121]:
officerCitizenCat = pd.get_dummies(tacoma[['id','officer_race', 'officer_sex','corrected_citizen_race', 'corrected_citizen_sex']])
tacomaEncoded = pd.concat([tacoma.groupby('id').first(), officerCitizenCat.groupby('id').sum()],axis = 1)

In [122]:
tacomaEncoded.head()

,city,state,address,district,sector,date,day_of_week,time,officer_race,officer_sex,officer_age,officer_years_of_service,citizen_race,citizen_sex,citizen_age,bad_gender,corrected_citizen_gender,corrected_citizen_race,corrected_citizen_sex,officer_race_Asian,officer_race_Black,officer_race_Hispanic,officer_race_White,officer_sex_Female,officer_sex_Male,corrected_citizen_race_Asian,corrected_citizen_race_Black,corrected_citizen_race_Hispanic,corrected_citizen_race_Nat Am,corrected_citizen_race_Native Amer,corrected_citizen_race_White,corrected_citizen_sex_Female,corrected_citizen_sex_Male
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
122440754,Tacoma,Washington,"809 S M St\nTacoma, Washington\n(47.254333, -1...",TA12,1.0,2012-08-31,Fri,15:40:00,White,Male,40,6.0,Black,Male,29,0,Male,Black,Male,0,0,0,1,0,1,0,1,0,0,0,0,0,1
122821213,Tacoma,Washington,"600 E 82nd St\nTacoma, Washington\n(47.18272, ...",TA44,4.0,2012-10-09,Mon,21:41:00,White,Male,29,5.0,White,Male,30,0,Male,White,Male,0,0,0,1,0,1,0,0,0,0,0,1,0,1
123571013,Tacoma,Washington,"3567 S Fawcett Ave\nTacoma, Washington\n(47.22...",TA43,4.0,2012-12-24,Sat,21:49:00,White,Male,36,7.0,Native Amer,Female,22,0,Female,Native Amer,Female,0,0,0,1,0,1,0,0,0,0,1,0,1,0
130581374,Tacoma,Washington,"3529 McKinley Ave\nTacoma, Washington\n(47.229...",TA41,4.0,2013-02-27,Wed,22:41:00,White,Male,38,3.0,White,Male,35,0,Male,White,Male,0,0,0,1,0,1,0,0,0,0,0,1,0,1
131800756,Tacoma,Washington,"2800 Portland Ave\nTacoma, Washington\n(47.238...",TA41,4.0,2013-06-29,Sat,15:05:00,White,Female,35,6.0,Hispanic,Male,25,0,Male,Hispanic,Male,0,0,0,1,1,0,0,0,1,0,0,0,0,1

## Cincinnati Ohio

In [159]:
cincinnati = dictOfDfs['Cincinnati Ohio'].copy()
cincinnati = cincinnati.drop(columns = [
    'INCIDENT_LOCATION_X',
    'INCIDENT_NO',
    'CFS_NO',
    'FIREARM_MAKE',
    'FIREARM_MODEL',
    'SNA_NEIGHBORHOOD',
    'CPD_NEIGHBORHOOD',
    'COMMUNITY_COUNCIL_NEIGHBORHOOD'
])
cincinnati.info()
cincinnati.columns = [
    'city',
    'state',
    'district',
    'x_coord',
    'y_coord',
    'date',
    'id',
    'incident_description',
    'citizen_sex',
    'citizen_race',
    'officer_sex',
    'officer_race'
]
cincinnati.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   City                  237 non-null    object
 1   State                 237 non-null    object
 2   DISTRICT              233 non-null    object
 3   LATITUDE_X            139 non-null    float64
 4   LONGITUDE_X           139 non-null    float64
 5   INCIDENT_DATE         237 non-null    datetime64[ns]
 6   CASE_NO               237 non-null    object
 7   INCIDENT_DESCRIPTION  237 non-null    object
 8   SUBJECT_GENDER        132 non-null    object
 9   SUBJECT_RACE          132 non-null    object
 10  OFFICER_GENDER        237 non-null    object
 11  OFFICER_RACE          237 non-null    object
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 22.3+ KB

,city,state,district,x_coord,y_coord,date,id,incident_description,citizen_sex,citizen_race,officer_sex,officer_race
0,Cincinnati,Ohio,DISTRICT 2,NaN,NaN,2006-01-29 12:57:00,2006-78254,WEAPON DISCHARGE AT AN ANIMAL,NaN,NaN,MALE,BLACK
1,Cincinnati,Ohio,DISTRICT 3,NaN,NaN,2016-01-11 20:00:00,2016-209015,USE OF FORCE INVESTIGATION,MALE,WHITE,MALE,WHITE
2,Cincinnati,Ohio,TRAINING SECTION,NaN,NaN,2013-06-03 07:40:00,2013-181381,ACCIDENTAL DISCHARGE,OTHER,UNKNOWN,MALE,WHITE
3,Cincinnati,Ohio,CENTRAL BUSINESS DISTRICT,NaN,NaN,2016-08-07 07:41:00,2016-215911,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,WHITE
4,Cincinnati,Ohio,DISTRICT 5,NaN,NaN,2018-05-03 00:09:00,2018-235541,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,WHITE

In [160]:
for x in cincinnati.columns:
    print(cincinnati[x].value_counts())

Cincinnati    237
Name: city, dtype: int64
Ohio    237
Name: state, dtype: int64
DISTRICT 3                   71
DISTRICT 4                   60
DISTRICT 5                   43
DISTRICT 2                   26
DISTRICT 1                   24
CIS                           4
CENTRAL BUSINESS DISTRICT     2
TRAINING SECTION              1
OUTSIDE CITY                  1
SSS                           1
Name: district, dtype: int64
39.175490    1
39.203293    1
39.108806    1
39.101149    1
39.121180    1
            ..
39.108296    1
39.128227    1
39.128686    1
39.145237    1
39.163781    1
Name: x_coord, Length: 139, dtype: int64
-84.455997    2
-84.430147    1
-84.528735    1
-84.488670    1
-84.413466    1
             ..
-84.523426    1
-84.645105    1
-84.500494    1
-84.515738    1
-84.581834    1
Name: y_coord, Length: 138, dtype: int64
2010-09-18 19:02:00    6
2014-06-04 18:20:00    4
2007-05-27 16:13:00    4
2009-11-17 11:15:00    3
2016-02-17 17:05:00    3
                      ..
2016-05-09 15:05:00    1
2012-03-19 15:32:00    1
2012-02-23 09:34:00    1
2006-09-05 01:18:00    1
2003-07-21 14:12:00    1
Name: date, Length: 199, dtype: int64
2010-148397    6
2014-191795    4
2007-99600     4
2009-138888    3
2005-69217     3
              ..
2015-198212    1
2008-115163    1
2007-104990    1
2014-194297    1
2015-200558    1
Name: id, Length: 200, dtype: int64
USE OF FORCE INVESTIGATION       119
WEAPON DISCHARGE AT AN ANIMAL    105
ACCIDENTAL DISCHARGE              13
Name: incident_description, dtype: int64
MALE      114
OTHER      14
FEMALE      4
Name: citizen_sex, dtype: int64
BLACK              95
WHITE              19
UNKNOWN            14
HISPANIC/LATINO     3
ASIAN               1
Name: citizen_race, dtype: int64
MALE      207
FEMALE     30
Name: officer_sex, dtype: int64
WHITE              154
BLACK               79
HISPANIC/LATINO      3
ASIAN                1
Name: officer_race, dtype: int64

In [161]:
cincinnatiShooting = cincinnati.copy().loc[cincinnati['incident_description'] == 'USE OF FORCE INVESTIGATION'].groupby(['id']).first()
cincinnatiShooting

,city,state,district,x_coord,y_coord,date,incident_description,citizen_sex,citizen_race,officer_sex,officer_race
id,,,,,,,,,,,
9600333,Cincinnati,Ohio,DISTRICT 3,NaN,NaN,1996-09-30 00:30:00,USE OF FORCE INVESTIGATION,MALE,WHITE,MALE,WHITE
9600518,Cincinnati,Ohio,DISTRICT 4,NaN,NaN,1996-10-26 02:40:00,USE OF FORCE INVESTIGATION,MALE,ASIAN,MALE,WHITE
9800189,Cincinnati,Ohio,DISTRICT 4,NaN,NaN,1998-03-04 23:32:00,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,WHITE
9800300,Cincinnati,Ohio,DISTRICT 1,NaN,NaN,1998-02-02 19:43:00,USE OF FORCE INVESTIGATION,MALE,BLACK,FEMALE,WHITE
9800443,Cincinnati,Ohio,NaN,NaN,NaN,1998-05-05 04:45:00,USE OF FORCE INVESTIGATION,MALE,WHITE,MALE,WHITE
...,...,...,...,...,...,...,...,...,...,...,...
2019-246738,Cincinnati,Ohio,DISTRICT 4,39.128686,-84.484054,2018-08-24 14:43:00,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,WHITE
2019-248398,Cincinnati,Ohio,DISTRICT 2,39.150831,-84.388074,2019-07-04 10:21:00,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,BLACK
2019-248765,Cincinnati,Ohio,DISTRICT 3,39.096373,-84.568387,2019-07-16 15:47:00,USE OF FORCE INVESTIGATION,FEMALE,BLACK,MALE,WHITE
2019-249505,Cincinnati,Ohio,DISTRICT 3,39.119091,-84.581834,2018-08-22 12:59:00,USE OF FORCE INVESTIGATION,FEMALE,BLACK,FEMALE,WHITE
2019-250226,Cincinnati,Ohio,SSS,NaN,NaN,2019-09-11 12:07:00,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,WHITE

In [162]:
officersSubjects = pd.get_dummies(cincinnatiShooting[['officer_race', 'officer_sex', 'citizen_race', 'citizen_sex']])

In [163]:
officersSubjectsCat = officersSubjects.groupby(['id']).sum()
cincinnatiShootingFirst = cincinnatiShooting.groupby(['id']).first()
cincinnatiEncoded = pd.concat([cincinnatiShootingFirst, officersSubjectsCat], axis = 1)
cincinnatiEncoded

,city,state,district,x_coord,y_coord,date,incident_description,citizen_sex,citizen_race,officer_sex,officer_race,officer_race_BLACK,officer_race_HISPANIC/LATINO,officer_race_WHITE,officer_sex_FEMALE,officer_sex_MALE,citizen_race_ASIAN,citizen_race_BLACK,citizen_race_HISPANIC/LATINO,citizen_race_UNKNOWN,citizen_race_WHITE,citizen_sex_FEMALE,citizen_sex_MALE,citizen_sex_OTHER
id,,,,,,,,,,,,,,,,,,,,,,,,
9600333,Cincinnati,Ohio,DISTRICT 3,NaN,NaN,1996-09-30 00:30:00,USE OF FORCE INVESTIGATION,MALE,WHITE,MALE,WHITE,0,0,1,0,1,0,0,0,0,1,0,1,0
9600518,Cincinnati,Ohio,DISTRICT 4,NaN,NaN,1996-10-26 02:40:00,USE OF FORCE INVESTIGATION,MALE,ASIAN,MALE,WHITE,0,0,1,0,1,1,0,0,0,0,0,1,0
9800189,Cincinnati,Ohio,DISTRICT 4,NaN,NaN,1998-03-04 23:32:00,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,WHITE,0,0,1,0,1,0,1,0,0,0,0,1,0
9800300,Cincinnati,Ohio,DISTRICT 1,NaN,NaN,1998-02-02 19:43:00,USE OF FORCE INVESTIGATION,MALE,BLACK,FEMALE,WHITE,0,0,1,1,0,0,1,0,0,0,0,1,0
9800443,Cincinnati,Ohio,NaN,NaN,NaN,1998-05-05 04:45:00,USE OF FORCE INVESTIGATION,MALE,WHITE,MALE,WHITE,0,0,1,0,1,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-246738,Cincinnati,Ohio,DISTRICT 4,39.128686,-84.484054,2018-08-24 14:43:00,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,WHITE,0,0,1,0,1,0,1,0,0,0,0,1,0
2019-248398,Cincinnati,Ohio,DISTRICT 2,39.150831,-84.388074,2019-07-04 10:21:00,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,BLACK,1,0,0,0,1,0,1,0,0,0,0,1,0
2019-248765,Cincinnati,Ohio,DISTRICT 3,39.096373,-84.568387,2019-07-16 15:47:00,USE OF FORCE INVESTIGATION,FEMALE,BLACK,MALE,WHITE,0,0,1,0,1,0,1,0,0,0,1,0,0
2019-249505,Cincinnati,Ohio,DISTRICT 3,39.119091,-84.581834,2018-08-22 12:59:00,USE OF FORCE INVESTIGATION,FEMALE,BLACK,FEMALE,WHITE,0,0,1,1,0,0,1,0,0,0,1,0,0
2019-250226,Cincinnati,Ohio,SSS,NaN,NaN,2019-09-11 12:07:00,USE OF FORCE INVESTIGATION,MALE,BLACK,MALE,WHITE,0,0,1,0,1,0,1,0,0,0,0,1,0

## Dallas Texas

In [151]:
dallas = dictOfDfs['Dallas Texas'].copy()
dallas.info()
dallas.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 13 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   City                                          251 non-null    object
 1   State                                         251 non-null    object
 2   Case #                                        251 non-null    object
 3   Date                                          251 non-null    datetime64[ns]
 4   Location                                      251 non-null    object
 5   Subject Deceased, Injured, or Shoot and Miss  251 non-null    object
 6   Subject Weapon                                251 non-null    object
 7   Subject(s)                                    251 non-null    object
 8   Officer(s)                                    251 non-null    object
 9   Grand Jury Disposition                        168 non-null    object
 10  Attorney General Forms URL                    31 non-null     object
 11  Summary URL                                   251 non-null    object
 12  GeoLocation                                   251 non-null    object
dtypes: datetime64[ns](1), object(12)
memory usage: 25.6+ KB

,City,State,Case #,Date,Location,"Subject Deceased, Injured, or Shoot and Miss",Subject Weapon,Subject(s),Officer(s),Grand Jury Disposition,Attorney General Forms URL,Summary URL,GeoLocation
0,Dallas,Texas,60045A,2013-03-14,2208 W. Northwest Highway,Deceased,Handgun,"Johnson, Tyrique B/M","Timms, Christopher B/M",No Bill,NaN,https://www.dallaspolice.net/reports/OIS/narra...,"2208 W Northwest Highway\nDallas, Texas\n(32.8..."
1,Dallas,Texas,165193-2016,2016-07-07,801 Main Street,Deceased,Assault Rifle,"Johnson, Micah B/M","Edwards, Henry W/M; Wells, Giovanni B/M; Junge...",No Bill,https://www.dallaspolice.net/reports/OIS/ag_fo...,https://www.dallaspolice.net/reports/OIS/narra...,"801 Main Street\nDallas, Texas\n(32.779453, -9..."
2,Dallas,Texas,254101-2014,2014-10-22,9770 Forest Lane,Shoot and Miss,Unarmed,"McGee, Gregory B/M","Johnson, Michael B/M",NaN,NaN,https://www.dallaspolice.net/reports/OIS/narra...,"9770 Forest Lane\nDallas, Texas\n(32.909415, -..."
3,Dallas,Texas,263673A,2013-10-14,9452 Crimnson Court,Injured,Knife,"Bennett, Bobby W/M","Spencer, Cardan B/M",True Bill,NaN,https://www.dallaspolice.net/reports/OIS/narra...,"9452 Crimnson Court\nDallas, Texas\n(32.669013..."
4,Dallas,Texas,203639-2016,2016-08-25,414 N Kramer,Deceased,Handgun,"Portillo, Elias L/M","Wagner, Christopher W/M",No Bill,https://www.dallaspolice.net/reports/OIS/ag_fo...,https://www.dallaspolice.net/reports/OIS/narra...,"414 N Kramer\nDallas, Texas\n(32.748632, -96.8..."
5,Dallas,Texas,251177-2016,2016-10-19,3500 Virginia Boulevard,Deceased,BB Gun,"Garcia, Anthony L/M","Guzman, Jose L/M",No Bill,https://www.dallaspolice.net/reports/OIS/ag_fo...,https://www.dallaspolice.net/reports/OIS/narra...,"3500 Virginia Boulevard\nDallas, Texas\n(32.74..."
6,Dallas,Texas,316668X,2010-11-16,8059 L.B.J. Freeway,Injured,Pellet Gun,"Williams, Joseph B/M","Felini, Michael W/M; Curtis, Guy W/M",No Bill,NaN,https://www.dallaspolice.net/reports/OIS/narra...,"8059 L B J Freeway\nDallas, Texas\n(32.924881,..."
7,Dallas,Texas,1004453N,2004-12-29,2400 Walnut Hill Lane,Shoot and Miss,Vehicle,"Evans, Jerry W/M","Nguyen, Buu A/M",NaN,NaN,https://www.dallaspolice.net/reports/OIS/narra...,"2400 Walnut Hill Lane\nDallas, Texas\n(32.8810..."
8,Dallas,Texas,884709M,2003-11-20,6300 C.F. Hawn Freeway,Shoot and Miss,Handgun,Unknown L/M,"Martin, Roger W/M",NaN,NaN,https://www.dallaspolice.net/reports/OIS/narra...,"6300 C F Hawn Freeway\nDallas, Texas\n(32.7336..."
9,Dallas,Texas,56628A,2013-03-10,3303 Southern Oaks Boulevard,Deceased,Hands,"Clinton, Allen B/M","Staller, Clark W/M",No Bill,NaN,https://www.dallaspolice.net/reports/OIS/narra...,"3303 Southern Oaks Boulevard\nDallas, Texas\n(..."

In [143]:
dallas['Case #'].value_counts()

236584A        1
161616-2016    1
042227-2018    1
302639Y        1
8025N          1
              ..
986476P        1
203505V        1
456826T        1
100044-2020    1
60944A         1
Name: Case #, Length: 251, dtype: int64

In [155]:
def get_awful_string(df, column):
    breakout = []
    for y in df[column].map(lambda x: x.split(' ')):
        tempList = []
        for k in range(len(y)):
            if ((k % 3)+1)% 3 == 0:
                tempList.append(y[k])
            else:
                continue
        breakout.append(tempList)
    return breakout
for x in get_awful_string(dallas,'Officer(s)'):
    print(''.join(x).split('/'))

['B', 'M']
['W', 'M;B', 'M;W', 'M;L', 'M;W', 'M;A', 'M;W', 'M;W', 'M;W', 'M;W', 'M;W', 'M;B', 'M']
['B', 'M']
['B', 'M']
['W', 'M']
['L', 'M']
['W', 'M;W', 'M']
['A', 'M']
['W', 'M']
['W', 'M']
['L', 'M']
['A', 'M']
['L', 'M;W', 'M;W', 'M;B', 'M']
['W', 'M;W', 'M;W', 'M;W', 'M;W', 'M']
['L', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['L', 'M']
['W', 'M']
['W', 'M;W', 'F']
['L', 'M']
['B', 'M']
['L', 'M']
['L', 'M']
['W', 'M;B', 'M;W', 'M;L', 'M']
['L', 'M']
['L', 'M']
['W', 'M']
['L', 'M;L', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['L', 'M']
['L', 'M']
['W', 'M;L', 'M']
['W', 'M']
['NA', 'M']
['W', 'M']
['B', 'M']
['B', 'M;W', 'M']
['W', 'M']
['W', 'M;W', 'M;W', 'M;W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M;W', 'M']
['L', 'M']
['W', 'M;L', 'M']
[',']
['B', 'M;B', 'M']
['L', 'M']
['W', 'M;L', 'M;W', 'M;B', 'M;W', 'M;W', 'M;W', 'M;W', 'M;B', 'M;W', 'M;W', 'M;W', 'M;W', 'M']
['W', 'M']
['L', 'M']
['B', 'F']
['W', 'M']
['B', 'M']
['B', 'M']
['W', 'M;W', 'M']
['L', 'M']
['W', 'M']
['W', 'M;L', 'M']
['L', 'M;W', 'F']
['L', 'M']
['W', 'M']
['W', 'F']
['B', 'M;B', 'M']
['NA', 'F']
['W', 'M']
['W', 'M;W', 'M;']
['NA', 'M']
['B', 'M']
['W', 'M']
['L', 'M']
['L', 'M']
['L', 'M']
['W', 'M']
['W', 'M;W', 'M;W', 'M;W', 'M;W', 'M;W', 'M;L', 'F;L', 'F;W', 'M;W', 'M;W', 'M;A', 'M,L', 'M;W', 'M;B', 'M;L', 'M']
['B', 'M']
['W', 'M']
['B', 'M']
['Jr.AlphonseTami']
['W', 'M']
['W', 'M']
['W', 'F']
['L', 'M']
['W', 'M;W', 'M;W', 'M;W', 'M;W', 'M']
['B', 'M']
['W', 'M']
['W', 'M;W', 'M']
['W', 'M']
['W', 'M']
['W', 'M;W', 'M']
['W', 'M;W', 'M']
['W', 'M']
['L', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['B', 'M']
['B', 'M']
['W', 'M']
['L', 'M;W', 'M;B', 'M']
['W', 'M;B', 'M']
['L', 'M;W', 'M;W', 'M']
['W', 'M']
['L', 'M;W', 'M;B', 'M']
['W', 'M;L', 'M']
['B', 'M']
['L', 'M']
['B', 'M;W', 'M;W', 'M;W', 'M;L', 'M']
['W', 'M;B', 'M']
['W', 'M']
['W', 'M']
['L', 'M;W', 'M']
['W', 'M']
['L', 'M;W', 'M']
['W', 'F']
['B', 'M;B', 'M']
['W', 'M;L', 'M']
['B', 'M']
['W', 'M']
['W', 'M;W', 'M']
['L', 'M;W', 'M;W', 'M;W', 'M']
['B', 'M']
['B', 'M']
['B', 'M']
['L', 'M;Jr.']
['B', 'M']
['W', 'F']
['A', 'M']
['A', 'M;W', 'M;L', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['L', 'M;W', 'M']
['W', 'M;W', 'M;W', 'M']
['W', 'M;W', 'M']
['B', 'M']
['W', 'M']
['Michael']
['W', 'M;W', 'M']
['']
['W', 'M']
['W', 'M']
['B', 'M']
['W', 'M;W', 'M;W', 'M;NA', 'M']
['W', 'M;W', 'M']
['W', 'M;B', 'F']
['L', 'M']
['L', 'M']
['A', 'M']
['W', 'M']
['B', 'M']
['L', 'M']
['W', 'MMarkDaniel']
['L', 'M']
['W', 'M;W', 'M']
['W', 'M']
['L', 'M']
['A', 'M']
['W', 'M;W', 'M;W', 'M;W', 'M']
['W', 'M']
['W', 'Mmondy,Owens,']
['B', 'M;B', 'F']
['L', 'M']
['B', 'M;B', 'F;B', 'F']
['W', 'M;W', 'M']
['B', 'M']
['W', 'M']
['B', 'M;B', 'M;B', 'M;L', 'M;B', 'M']
['B', 'F;L', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['A', 'M']
['Philip']
['L', 'M']
['Jr.St.Jr.']
['L', 'M']
['L', 'M']
['B', 'M']
['B', 'M']
['W', 'M']
['W', 'M']
['B', 'M']
['B', 'M']
['L', 'M']
['L', 'M']
['W', 'M;L', 'F']
['L', 'M']
['A', 'MEvans,Gonzalez,']
['L', 'M']
['B', 'M']
['W', 'M;W', 'M']
['W', 'M;W', 'M']
['W', 'M']
['B', 'M;W', 'M']
['W', 'M;W', 'M']
['Matthew']
['W', 'M;W', 'M;L', 'M;W', 'M;W', 'M']
['B', 'M']
['Jr.']
['B', 'M']
['W', 'M']
['W', 'F;W', 'M']
['W', 'M']
['W', 'M']
['B', 'M']
['L', 'F']
['W', 'M']
['W', 'M']
['W', 'M']
['L', 'M']
['W', 'M']
['W', 'M']
['B', 'M']
['W', 'M']
['A', 'M']
['L', 'M;W', 'M']
['W', 'M']
['W', 'M']
['W', 'M']
['W', 'M;W', 'M;W', 'M;W', 'M;W', 'M']
['L', 'M']
['W', 'M;W', 'M;W', 'M;B', 'M;W', 'M;W', 'M;W', 'M;L', 'M']
['L', 'M;L', 'M']
['W', 'M;W', 'M']
['L', 'M']
['W', 'M']
['B', 'M;L', 'M;L', 'M']
['B', 'M']
['W', 'M;B', 'M;B', 'M;B', 'M']
['W', 'M']
['W', 'M;W', 'M;B', 'M;B', 'M;W', 'F;L', 'M;B', 'M;W', 'M;L', 'M']
['B', 'M']
['L', 'M']
['L', 'M']
['W', 'M']
['W', 'M']
['L', 'M']
['L', 'M']

<!-- for x in get_awful_string(dallas,'Subject(s)'): -->

In [145]:
dallas['x_y_coord'] = dallas.GeoLocation.map(lambda x: x.replace('(', '').replace(',','').replace(')','').strip().split()[-2:])

In [146]:
dallas.columns

Index(['City', 'State', 'Case #', 'Date', 'Location',
       'Subject Deceased, Injured, or Shoot and Miss', 'Subject Weapon',
       'Subject(s)', 'Officer(s)', 'Grand Jury Disposition',
       'Attorney General Forms URL', 'Summary URL', 'GeoLocation',
       'x_y_coord'],
      dtype='object')

In [147]:
dallas.drop(columns = ['Case #', 'Grand Jury Disposition',
       'Attorney General Forms URL', 'Summary URL', 'GeoLocation'])

,City,State,Date,Location,"Subject Deceased, Injured, or Shoot and Miss",Subject Weapon,Subject(s),Officer(s),x_y_coord
0,Dallas,Texas,2013-03-14,2208 W. Northwest Highway,Deceased,Handgun,"Johnson, Tyrique B/M","Timms, Christopher B/M","[32.8641, -96.898998]"
1,Dallas,Texas,2016-07-07,801 Main Street,Deceased,Assault Rifle,"Johnson, Micah B/M","Edwards, Henry W/M; Wells, Giovanni B/M; Junge...","[32.779453, -96.804915]"
2,Dallas,Texas,2014-10-22,9770 Forest Lane,Shoot and Miss,Unarmed,"McGee, Gregory B/M","Johnson, Michael B/M","[32.909415, -96.718739]"
3,Dallas,Texas,2013-10-14,9452 Crimnson Court,Injured,Knife,"Bennett, Bobby W/M","Spencer, Cardan B/M","[32.669013, -96.662659]"
4,Dallas,Texas,2016-08-25,414 N Kramer,Deceased,Handgun,"Portillo, Elias L/M","Wagner, Christopher W/M","[32.748632, -96.878279]"
...,...,...,...,...,...,...,...,...,...
246,Dallas,Texas,2019-04-06,2500 S. Vernon Ave.,Shoot and Miss,Vehicle,"Garcia, Abraham L/M","Rojo, Aldo L/M","[32.721806, -96.836167]"
247,Dallas,Texas,2003-03-18,14655 Preston Road,Deceased,Shotgun,"Bannister, James W/M","Guynn, Byron W/M","[32.947548, -96.803614]"
248,Dallas,Texas,2013-03-15,9147 Skillman Street,Shoot and Miss,BB Gun,"Jones, Christopher B/M","Tholl, Kyle W/M","[32.902101, -96.717073]"
249,Dallas,Texas,2019-03-22,10666 E. Northwest Hwy.,Injured,Handgun,"Jasso, Santiago L/M; Portillo, Oscar L/M","Amaya, Juan L/M","[32.864037, -96.701106]"
250,Dallas,Texas,2006-05-09,5500 Bernal Drive,Shoot and Miss,Handgun,"Rodriguez, Robert Jr. L/M","Lopez, Antonio L/M","[32.775979, -96.911343]"

## Hartford Conneticut

In [74]:
hartford = dictOfDfs['Hartford Conneticut'].copy()
hartford.info()
hartford.drop(columns = [
    'Address',
    'UCR_1_Category',
    'UCR_2_Category',
    'UCR_1_Code',
    'UCR_2_Code'
])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               89 non-null     object
 1   State              89 non-null     object
 2   Case_Number        89 non-null     int64
 3   Date               89 non-null     datetime64[ns]
 4   Time_24HR          89 non-null     int64
 5   Address            89 non-null     object
 6   UCR_1_Category     89 non-null     object
 7   UCR_1_Description  89 non-null     object
 8   UCR_1_Code         89 non-null     int64
 9   UCR_2_Category     76 non-null     object
 10  UCR_2_Description  76 non-null     object
 11  UCR_2_Code         89 non-null     int64
 12  Neighborhood       89 non-null     object
 13  geom               89 non-null     object
dtypes: datetime64[ns](1), int64(4), object(9)
memory usage: 9.9+ KB

,City,State,Case_Number,Date,Time_24HR,UCR_1_Description,UCR_2_Description,Neighborhood,geom
0,Hartford,Connecticut,19037774,2019-11-21,1440,SHOOTING-INJ,RECKLESS END 1,FROG HOLLOW,"(41.76221240514027, -72.69518931015217)"
1,Hartford,Connecticut,19038163,2019-11-25,1504,PD-SHOOTING,ANIMAL COMPLNT,SOUTHWEST,"(41.72656736192673, -72.69877001050818)"
2,Hartford,Connecticut,19039337,2019-12-06,1121,PD-SHOOTING,ANIMAL COMPLNT,SOUTH GREEN,"(41.757536822683626, -72.6775877244074)"
3,Hartford,Connecticut,19040389,2019-12-13,2326,PD-SHOOTING,ANIMAL BITE,CLAY-ARSENAL,"(41.777946086198725, -72.68211553566037)"
4,Hartford,Connecticut,20000239,2020-01-02,2036,PD-SHOOTING,ANIMAL COMPLNT,BEHIND THE ROCKS,"(41.739999911143904, -72.69672515790272)"
...,...,...,...,...,...,...,...,...,...
84,Hartford,Connecticut,18034803,2018-11-16,1055,PD-SHOOTING,NaN,CLAY-ARSENAL,"(41.78077611289366, -72.68439426599812)"
85,Hartford,Connecticut,5019664,2005-05-07,1924,PD-SHOOTING,FATAL SHOOTING,NORTHEAST,"(41.786822387292226, -72.67355559756052)"
86,Hartford,Connecticut,7006629,2007-02-16,2210,RECKLESS END 1,SHOOTING-INJ,NORTHEAST,"(41.78568000046961, -72.68122999999389)"
87,Hartford,Connecticut,11002573,2011-01-23,151,PD-SHOOTING,OCC-INJ-POLICE,WESTEND,"(41.76680072076744, -72.70830864001476)"
88,Hartford,Connecticut,14022149,2014-07-06,1807,SHOOTING-MISS,ANIMAL COMPLNT,SOUTHEND,"(41.733873488432984, -72.6724687505705)"

In [75]:
hartford['UCR_2_Description'].value_counts()

ANIMAL COMPLNT    27
SHOOTING-INJ      21
SHOOTING-MISS      7
PD-SHOOTING        7
FATAL SHOOTING     5
RECKLESS END 1     3
ANIMAL BITE        3
BREACH-PEACE       1
RISK OF INJURY     1
OCC-INJ-POLICE     1
Name: UCR_2_Description, dtype: int64

### Getting rid of animal shootings

In [76]:
hartfordShooting = hartford.loc[(hartford['UCR_2_Description'] != 'ANIMAL COMPLNT') & 
                                (hartford['UCR_2_Description'] != 'ANIMAL BITE') & 
                                (hartford['UCR_1_Description'] != 'ANIMAL COMPLNT')]
hartfordShooting.loc[(hartfordShooting['UCR_1_Description'] == 'SHOOTING-INJ') | 
                     (hartfordShooting['UCR_2_Description'] == 'SHOOTING-INJ')]

hartfordShooting.loc[(hartfordShooting['UCR_1_Description'] == 'SHOOTING-MISS') | 
                     (hartfordShooting['UCR_2_Description'] == 'SHOOTING-MISS')]

hartfordShooting.loc[(hartfordShooting['UCR_1_Description'] == 'FATAL SHOOTING') | 
                     (hartfordShooting['UCR_2_Description'] == 'FATAL SHOOTING')]

,City,State,Case_Number,Date,Time_24HR,Address,UCR_1_Category,UCR_1_Description,UCR_1_Code,UCR_2_Category,UCR_2_Description,UCR_2_Code,Neighborhood,geom
13,Hartford,Connecticut,15017598,2015-06-09,1915,144 WESTMINSTER ST,04* - AGGRAVATED ASSAULT,ASSLT-PO-KNIFE,422,49* - SHOOTING,FATAL SHOOTING,4901,BLUE HILLS,"(41.79747742497788, -72.70259793482641)"
26,Hartford,Connecticut,13015945,2013-05-15,2201,24 HEATH ST,49* - SHOOTING,PD-SHOOTING,4900,49* - SHOOTING,FATAL SHOOTING,4901,PARKVILLE,"(41.75712035776425, -72.71072519222501)"
28,Hartford,Connecticut,12023809,2012-07-11,105,60 WADSWORTH ST,49* - SHOOTING,PD-SHOOTING,4900,49* - SHOOTING,FATAL SHOOTING,4901,SOUTH GREEN,"(41.75904174484983, -72.67915721701848)"
83,Hartford,Connecticut,19024187,2019-07-26,2154,I 84W-EXIT 48 ON RAMP,49* - SHOOTING,PD-SHOOTING,4900,49* - SHOOTING,FATAL SHOOTING,4901,ASYLUM HILL,"(41.7664585150635, -72.6871952543044)"
85,Hartford,Connecticut,5019664,2005-05-07,1924,2374 MAIN ST,49* - SHOOTING,PD-SHOOTING,4900,49* - SHOOTING,FATAL SHOOTING,4901,NORTHEAST,"(41.786822387292226, -72.67355559756052)"

### Creating injury column from ucr description

In [77]:
hartfordShooting['UCR_2_Description'].isin(['SHOOTING-INJ',])

0     False
6      True
7      True
9      True
10    False
      ...
83    False
84    False
85    False
86     True
87    False
Name: UCR_2_Description, Length: 54, dtype: bool

### Reducing features

In [78]:
ucr1_description_map = {
    ''
}

In [79]:
hartfordShooting['UCR_1_Description'].value_counts()

RECKLESS END 1              18
PD-SHOOTING                 12
SHOOTING-INJ                 9
ASSLT-PO-WEAPON              5
SHOOTING-MISS                2
RISK OF INJURY               1
CRUELTY/ANIMAL               1
SUDDEN DEATH                 1
PD/VEH/ACC/MI*MULT-INJ*      1
RECOVERED STOLEN FIREARM     1
ROBBERY-GUN *STREET*         1
ASSLT-PO-GUN                 1
ASSLT-PO-KNIFE               1
Name: UCR_1_Description, dtype: int64

In [80]:
hartfordShooting['UCR_2_Description'].value_counts()

SHOOTING-INJ      21
PD-SHOOTING        6
FATAL SHOOTING     5
RECKLESS END 1     3
SHOOTING-MISS      3
BREACH-PEACE       1
OCC-INJ-POLICE     1
RISK OF INJURY     1
Name: UCR_2_Description, dtype: int64

In [81]:
hartford['UCR_1_Category'].map(lambda x: x.replace('-','').replace('*','').split()[-1])

0     SHOOTING
1     SHOOTING
2     SHOOTING
3     SHOOTING
4     SHOOTING
        ...
84    SHOOTING
85    SHOOTING
86     ASSAULT
87    SHOOTING
88    SHOOTING
Name: UCR_1_Category, Length: 89, dtype: object

## Indianapolis Indiana

### Intro data exploration

In [169]:
indianapolis = dictOfDfs['Indianapolis Indiana']
indianapolis.info()
indianapolis.columns = [
    'city',
    'state',
    'id',
    'date',
    'division',
    'district',
    'shift',
    'beat',
    'disposition',
    'citizen_armed',
    'officer_armed',
    'incident_initiation',
    'citizen_injury',
    'officer_injury',
    'citizen_race',
    'citizen_sex',
    'citizent_age',
    'officer_race',
    'officer_sex',
    'officer_age',
    'officer_years_of_service',
    'officer_identifier'
]
# indianapolis = indianapolis.drop(columns = [
#     'officerWeaponUsed',
#     'beat', 
#     'disposition', 
#     'officerIdentifier'
# ])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   City                   54 non-null     object
 1   State                  54 non-null     object
 2   id                     54 non-null     object
 3   occurredDate           53 non-null     datetime64[ns]
 4   division               53 non-null     object
 5   district               53 non-null     object
 6   shift                  53 non-null     object
 7   beat                   6 non-null      object
 8   disposition            1 non-null      object
 9   residentWeaponUsed     41 non-null     object
 10  officerWeaponUsed      51 non-null     object
 11  serviceType            33 non-null     object
 12  residentCondition      49 non-null     object
 13  officerCondition       20 non-null     object
 14  residentRace           53 non-null     object
 15  residentSex            53 non-null     object
 16  residentAge            53 non-null     float64
 17  officerRace            52 non-null     object
 18  officerSex             53 non-null     object
 19  officerAge             53 non-null     float64
 20  officerYearsOfService  53 non-null     float64
 21  officerIdentifier      53 non-null     object
dtypes: datetime64[ns](1), float64(3), object(18)
memory usage: 9.4+ KB

In [170]:
for x in indianapolis.columns:
    print(indianapolis[x].value_counts());

Indianapolis    54
Name: city, dtype: int64
Indiana    54
Name: state, dtype: int64
1b3c48c6f44d0af6944812bf740a9cce    6
ca175186383abf3ed448cb22df346753    3
5b724ceb1dfbb2bbcfa25102b30ba55a    3
bb5c59502f5d1b3834cc8e97638146e4    2
a1bf412e46bc7a9377813d6859b04979    2
dc503d13c8ff990a1edc0d1e69f0bf1a    2
03221d6cbd5478dc62ea6a0603d9d90d    2
658455897d58d7dff125447e51d83846    2
402e46b147ecbc9c6fa8d9b11e08714f    2
55ac7711fc0a8e42707070d3526d00bf    2
cd314cea50e8fa57d5d49eb1af53dbfd    2
da659547952913021f57cea0af21d540    1
52a0eb13a62ef588e55976df0537a01d    1
a5cd96363355d77224357c89a716483c    1
b055ef4be4958bea407cc0bbd2cf0c53    1
cfa745b4166916266a70fb1f3a95510d    1
2e6d0b4e9b9340cec135bec91da82b22    1
580df496c6c5bfde500e0b21ef2ce95b    1
41622a20fedd9cba24e690f246c687f4    1
a4aee5eed92ac486c08ecbf99511f1e7    1
66745f1f48d425a018634f5f38851add    1
c3d025a3d32bdc49ecc0efa0e0fb1fa3    1
f3923c0b16fbbcaef2231c95236ae35f    1
893f13656351c59dd0e2f9d5140754cc    1
3f1ea97f02bb3c0f3630d0442c041064    1
028a1f6a21dbb4856c41d1f0510db606    1
d2ca48c773442634d0be6439a5672cd8    1
122aabf48ef2899f6ba743e252e2c2a9    1
f76ebd21fab2689799bde44abad020e2    1
ca32440fdb0c85aef1fb233140a34da0    1
b4686516232d2341b7142ce2e3923704    1
eb352ebb060f3b08d633e8726ea2f27c    1
975655df00044cba3a6fc662f2e98510    1
894307a273acd20daa875c096cac5e10    1
25fbcadc17452a0562780752f151ac6a    1
e833decf38d67c4986c57234555400cf    1
433a0a8e8cb49fbb560b458d14d91947    1
Name: id, dtype: int64
2015-04-06    6
2015-08-09    3
2015-03-22    3
2015-12-12    2
2016-08-11    2
2015-04-12    2
2015-08-17    2
2015-02-21    2
2014-08-10    2
2015-12-10    2
2015-07-26    2
2018-11-09    1
2015-01-02    1
2016-04-02    1
2015-07-20    1
2015-01-15    1
2014-01-01    1
2015-03-11    1
2016-08-23    1
2016-03-08    1
2014-10-18    1
2015-01-10    1
2014-12-13    1
2015-10-05    1
2016-12-12    1
2015-08-29    1
2016-01-07    1
2014-11-10    1
2014-10-29    1
2015-06-23    1
2016-08-01    1
2015-10-26    1
2014-11-24    1
2015-06-14    1
2016-04-05    1
2017-03-05    1
Name: date, dtype: int64
Operations Division           50
Reserves                       2
Homeland Security Division     1
Name: division, dtype: int64
North District                       15
Northwest District                   11
East District                        10
Southwest District                    9
Southeast District                    5
Platoon 4                             1
Platoon 3                             1
Homeland Security Bureau/Tactical     1
Name: district, dtype: int64
NW Late Shift      9
ND Late Shift      8
SW Late Shift      8
ED Middle Shift    5
ND Middle Shift    5
ED Late Shift      3
SE Middle Shift    3
ND Day Shift       2
ED Day Shift       2
NW Middle Shift    2
SE Late Shift      1
Squad 2            1
SE Day Shift       1
SW Middle Shift    1
Canine Section     1
Squad 1            1
Name: shift, dtype: int64
ED Day Shift                  2
ND Day Shift                  2
Canine Unit - Day Tactical    1
SE Day Shift 2nd Rc           1
Name: beat, dtype: int64
Not Justified    1
Name: disposition, dtype: int64
Handgun        25
Unarmed         7
Knife           4
Misc Weapon     3
Rifle           2
Name: citizen_armed, dtype: int64
IMPD - Duty Handgun      43
Personal Patrol Rifle     2
Duty Handgun              2
IMPD - Patrol Rifle       2
IMPD - Shotgun            1
Personal Shotgun          1
Name: officer_armed, dtype: int64
Call For Service    21
Investigation        6
Traffic Stop         4
Warrant Service      1
Not Applicable       1
Name: incident_initiation, dtype: int64
Gunshot Wound                   38
No injuries noted or visible     7
Death                            4
Name: citizen_injury, dtype: int64
No injuries noted or visible    17
Gunshot Wound                    2
Minor Scrapes                    1
Name: officer_injury, dtype: int64
Black       30
White       19
Hispanic     2
Unknown      2
Name: citizen_race, dtype: int64
Male      52
Female     1
Name: citizen_sex, dtype: int64
23.0    9
19.0    7
34.0    4
25.0    3
31.0    3
21.0    3
15.0    3
37.0    2
27.0    2
51.0    2
17.0    1
29.0    1
32.0    1
22.0    1
42.0    1
28.0    1
24.0    1
18.0    1
33.0    1
47.0    1
30.0    1
45.0    1
36.0    1
48.0    1
41.0    1
Name: citizent_age, dtype: int64
White    44
Black     7
Asian     1
Name: officer_race, dtype: int64
Male      51
Female     2
Name: officer_sex, dtype: int64
29.0    6
36.0    5
33.0    4
37.0    3
39.0    3
40.0    3
28.0    3
31.0    3
35.0    2
44.0    2
48.0    2
50.0    2
59.0    1
52.0    1
38.0    1
32.0    1
42.0    1
30.0    1
47.0    1
51.0    1
27.0    1
34.0    1
55.0    1
45.0    1
23.0    1
46.0    1
61.0    1
Name: officer_age, dtype: int64
5.0     7
14.0    5
13.0    5
8.0     4
6.0     4
11.0    3
4.0     3
12.0    3
15.0    2
17.0    2
1.0     2
3.0     2
7.0     2
10.0    2
16.0    1
29.0    1
27.0    1
18.0    1
28.0    1
9.0     1
33.0    1
Name: officer_years_of_service, dtype: int64
ef4767a4e1d7e5c972ea013133232446    2
b7b843e28fd235e2af03ce3503659b97    2
7dbc981949703f8d9eb0cc2b617cd844    1
71e88311a045d66d2ef8404a57f905c6    1
42fe7c51b27f7eda6320bec302902652    1
                                   ..
56d6c89431eaf8dbe2e79b63b3c8cd92    1
a4bff69d0bc8af0da01e62cdcc2f0d65    1
07c216294c07116ab8800137fb2f2cf8    1
d27949e66c2e22b825d0945d5bfeba27    1
2d75bd8f411085af3178a17b02fbcb04    1
Name: officer_identifier, Length: 51, dtype: int64

In [174]:
race_map = {
    'White' : 'white',
    'WHITE' : 'white',
    'W' : 'white',
    'w' : 'white',
    'Black': 'black',
    'BLACK': 'black',
    'B' : 'black',
    'b' : 'black',
    'Hispanic': 'hispanic',
    'HISPANIC' : 'hispanic',
    'H' : 'hispanic',
    'h' : 'hispanic',
    'Unknown' : 'unknown',
    'UNK' : 'unknown',
    'UNKNOWN' : 'unknown'
}

sex_map = {
    'MALE': 'male',
    'Male' : 'male',
    'M' : 'male',
    'm' : 'male',
    'FEMALE' : 'female',
    'Female' : 'female',
    'F' : 'female',
    'f' : 'female'
}

indianapolis['officer_race'] = indianapolis['officer_race'].map(race_map)
indianapolis['citizen_race'] = indianapolis['citizen_race'].map(race_map)
indianapolis['citizen_sex'] = indianapolis['citizen_sex'].map(sex_map)
indianapolis['officer_sex'] = indianapolis['officer_sex'].map(sex_map)

In [175]:

officers = pd.concat([indianapolis['id'],pd.get_dummies(indianapolis[['officer_race','officer_sex']])], axis = 1)
officersGrouped = officers.groupby(['id']).sum()
indianapolisThing = indianapolis.groupby(['id']).first()
indianapolisEncoded = pd.concat([indianapolisThing, officersGrouped], axis = 1).reset_index()
indianapolisEncoded.head()

,id,city,state,date,division,district,shift,beat,disposition,citizen_armed,officer_armed,incident_initiation,citizen_injury,officer_injury,citizen_race,citizen_sex,citizent_age,officer_race,officer_sex,officer_age,officer_years_of_service,officer_identifier,officer_sex_female,officer_sex_male
0,028a1f6a21dbb4856c41d1f0510db606,Indianapolis,Indiana,2015-10-05,Reserves,Platoon 4,Squad 2,NaN,NaN,Handgun,IMPD - Duty Handgun,Investigation,NaN,No injuries noted or visible,NaN,male,47.0,NaN,male,34.0,11.0,7efe6cc87736398ca74644d46db534d2,0,1
1,03221d6cbd5478dc62ea6a0603d9d90d,Indianapolis,Indiana,2015-08-17,Operations Division,North District,ND Late Shift,NaN,NaN,Handgun,IMPD - Duty Handgun,Investigation,Gunshot Wound,No injuries noted or visible,NaN,male,21.0,NaN,male,51.0,13.0,c971e97de8fe33ecb13576dbd2f1a4c4,0,2
2,122aabf48ef2899f6ba743e252e2c2a9,Indianapolis,Indiana,2014-10-29,Operations Division,North District,ND Day Shift,ND Day Shift,NaN,Handgun,IMPD - Duty Handgun,Call For Service,No injuries noted or visible,No injuries noted or visible,NaN,male,29.0,NaN,male,52.0,29.0,a4bff69d0bc8af0da01e62cdcc2f0d65,0,1
3,1b3c48c6f44d0af6944812bf740a9cce,Indianapolis,Indiana,2015-04-06,Operations Division,Southwest District,SW Late Shift,NaN,NaN,Handgun,IMPD - Duty Handgun,Call For Service,Gunshot Wound,NaN,NaN,male,23.0,NaN,male,48.0,14.0,7d743deffb658ef13a3973bf14cb4638,2,4
4,25fbcadc17452a0562780752f151ac6a,Indianapolis,Indiana,2014-12-13,Operations Division,North District,ND Middle Shift,NaN,NaN,Unarmed,IMPD - Duty Handgun,Call For Service,Gunshot Wound,No injuries noted or visible,NaN,male,42.0,NaN,male,29.0,4.0,07c216294c07116ab8800137fb2f2cf8,0,1

## Orlando Florida

In [86]:
orlando = dictOfDfs['Orlando Florida'].copy()
orlando.info()
orlando.drop(columns = [
    'Review Letter',
    'Georeferenced Column'
])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   City                         65 non-null     object
 1   State                        65 non-null     object
 2   Case #                       65 non-null     object
 3   Date                         65 non-null     datetime64[ns]
 4   Address                      65 non-null     object
 5   Incident Type                65 non-null     object
 6   Number of Officers Involved  65 non-null     int64
 7   Officer Name                 65 non-null     object
 8   Officer Race                 65 non-null     object
 9   Ethnicity                    61 non-null     object
 10  Officer Gender               65 non-null     object
 11  Officer Age                  65 non-null     object
 12  Officer Tenure               65 non-null     object
 13  Number of Suspects Involved  65 non-null     int64
 14  Suspect Name                 65 non-null     object
 15  Suspect Race                 65 non-null     object
 16  Suspect Gender               65 non-null     object
 17  Suspect Age                  65 non-null     object
 18  Suspect's Weapon             65 non-null     object
 19  Suspect Hit                  65 non-null     object
 20  Fatal                        65 non-null     object
 21  Officer Hit                  65 non-null     object
 22  Fatal (Officer)              65 non-null     object
 23  Review Letter                59 non-null     object
 24  Georeferenced Column         50 non-null     object
dtypes: datetime64[ns](1), int64(2), object(22)
memory usage: 12.8+ KB

,City,State,Case #,Date,Address,Incident Type,Number of Officers Involved,Officer Name,Officer Race,Ethnicity,Officer Gender,Officer Age,Officer Tenure,Number of Suspects Involved,Suspect Name,Suspect Race,Suspect Gender,Suspect Age,Suspect's Weapon,Suspect Hit,Fatal,Officer Hit,Fatal (Officer)
0,Orlando,Florida,11-257484,2011-06-10,400 S. Parramore,Drug Violation,1,"Ochiuzzo, Matt",W,N,M,28,5,1,"Fell,Ronnery",Black,M,27,Hands/reaching,Yes,No,No,No
1,Orlando,Florida,18-228375,2018-06-10,4832 Eaglesmere Drive,Battery,1,"Gonzalez, Emanuel",W,H,M,30,1,1,"Lindsey, Gary",White,M,35,Handgun,Undetermined,Self-Inflicted,No,No
2,Orlando,Florida,20-60687,2020-02-18,"4567 S. Kirkman Rd. Orlando, FL 32811",Occupied Stolen Vehicle,2,"Chisari, Ben; Madison, Jeffery","W, B",NaN,"M, M","38, 39","9, 1",1,"Aldophe, Kevin",Black,M,22,Handgun,Yes,Yes,No,No
3,Orlando,Florida,13-237300,2013-06-10,I4/Livingston,Armed Subject,4,"D'Amato, Greg; Broadhurst, Blake; Edwards, Mic...","W, B, B, W","N, N, N, N","M, M, F, M","41, 30, 29, 33","11, 5, 0.25, 4",1,"Paige, Joseph",Black,M,24,Handgun,Yes,Yes,"No, No, No, No","No, No, No, No"
4,Orlando,Florida,18-373194,2018-09-25,5055 City Street,Unknown Trouble,4,"Goncalves, Gustavo; Barber, Alex; Gonzalez, Em...","W,W,W,W","H,W,H,W","M,M,M,M","36,28,30,28","1,1,1,1",1,"Burch, Dravious Lavon Sr.",Black,M,34,Handgun (2),Yes,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Orlando,Florida,18-414226,2018-10-26,3936 W D Judge Drive,Violent Mentally Ill Person,1,"Wright, Norman; Costa, Robert","B,W","N,H","M,M","48,57","46,51",1,"Counts,Tymeke",Black,M,18,Handgun,No,No,No,No
61,Orlando,Florida,13-495877,2013-11-25,Thorpe/Wentwood,Traffic Stop,1,"Briscoe, Derek",W,N,M,30,4,1,"Leggitt, Brian",White,M,31,Motor Vehicle,Yes,Yes,No,No
62,Orlando,Florida,09-212879,2009-05-06,25 W Church Street,Traffic Crash,2,"Alban, David; Brady, Daniel","W, W","H, N","M, M","34, 35","4, 12",1,"Delices, Vales",Black,M,23,Motor Vehicle,Yes,Yes,"No, No","No, No"
63,Orlando,Florida,14-211161,2014-05-21,4449 Malibu Dr,Armed Robbery,2,"Mongeluzzo, Anthony; Goss, Aaron","W, W","N, N","M, M","35, 34","7, 5",1,"Rodgers, Jermassioun",Black,M,20,Handgun,Yes,Yes,"No, No","No, No"
64,Orlando,Florida,14-443123,2014-10-24,2301 29 th Street,Suspicious Vehicle,1,"Avignon, Stanley",B,N,M,32,1,1,Unknown,Black,M,unk,Motor Vehicle,No,No,No,No

In [87]:
for x in orlando.columns:
    print(orlando[x].value_counts())

Orlando    65
Name: City, dtype: int64
Florida    65
Name: State, dtype: int64
11-306389    1
17-075014    1
14-443123    1
13-301648    1
11-201994    1
            ..
14-345320    1
18-379906    1
12-073698    1
11-521034    1
13-022948    1
Name: Case #, Length: 65, dtype: int64
2009-05-06    2
2012-02-19    2
2018-10-01    1
2012-07-03    1
2014-10-24    1
             ..
2016-05-01    1
2014-05-22    1
2015-07-13    1
2018-09-25    1
2014-02-24    1
Name: Date, Length: 63, dtype: int64
390 N Orange                                       1
4400 Block Martins Way                             1
2124 W. Colonial Dr. Orlando, FL32804              1
118 S. Orange Ave                                  1
Hiawassee & SR 50                                  1
                                                  ..
2 S. Orange Ave                                    1
1657 Watauga Way                                   1
Jamil/Central                                      1
Bowen DR at Folkstone                              1
555 North John Young Parkway, Orlando, FL 32811    1
Name: Address, Length: 65, dtype: int64
Traffic Stop                                                                                         7
Armed Robbery                                                                                        5
Armed Subject                                                                                        4
Suspicious Person                                                                                    4
Shots fired                                                                                          3
Battery                                                                                              3
Stolen Vehicle                                                                                       3
Attempted Suicide                                                                                    3
Homicide                                                                                             2
Carjacking                                                                                           2
Attempted Murder                                                                                     2
Drug Violation                                                                                       2
Occupied Stolen Vehicle                                                                              1
Robbery with a Firearm                                                                               1
Unknown Trouble                                                                                      1
Shoplifiting                                                                                         1
Stalking                                                                                             1
Attempt to Contact                                                                                   1
Felony Warrant                                                                                       1
Vehicle Burglary                                                                                     1
Fraud                                                                                                1
Traffic Crash                                                                                        1
Barricaded Subject                                                                                   1
Aggravated Assault                                                                                   1
Aggravated Assault on a Law Enforcement Officer with a Deadly Weapon, Armed Kidnapping (3 counts)    1
Aggravated Battery                                                                                   1
Well Being Check                                                                                     1
Suspicious Incident                                                                                  1
Active Shooter                                                                                       1
Street Racing                                                                                        1
Suspicious Incident / Possible Kidnapping                                                            1
Suspicious Vehicle                                                                                   1
Burglary                                                                                             1
Disturbance                                                                                          1
Threats/Assault                                                                                      1
Violent Mentally Ill Person                                                                          1
Atempted Murder                                                                                      1
Name: Incident Type, dtype: int64
1     41
2     12
3      6
4      3
5      2
11     1
Name: Number of Officers Involved, dtype: int64
Fischer, Bryan                                                                  2
Lamont, Travis; Negron, Alberto; Chisari, Ben                                   1
Falbo, James                                                                    1
Bruns, Dan; Stallworth, Danny                                                   1
Randall, Remy                                                                   1
                                                                               ..
Cruz, David                                                                     1
Villaverde, Carlos                                                              1
Falbo,James; Clough, Philip; Stites, Sammy; Bakeman, Bradley; Ospina, Rafael    1
Toler, Jimmie                                                                   1
Michael, Edward                                                                 1
Name: Officer Name, Length: 64, dtype: int64
W                                 32
W, W                               7
B                                  4
O                                  3
W, B                               3
W, W, W, W, W                      2
W, W, W                            2
W, B, W                            1
W,W, W, W, W, B, W, W, B, W, W     1
W, B, B, W                         1
W, O, W                            1
B,W                                1
W,W                                1
W,W,W                              1
O,W                                1
B, W, W                            1
B, W, W, W                         1
W,W,W,W                            1
Exempt                             1
Name: Officer Race, dtype: int64
N                                 29
H                                  8
N, N                               6
N, N, N                            4
H, N                               2
N, N, N, N, N                      2
N, H, N                            1
N, N, N, N                         1
N, N, H, N                         1
W,W                                1
N,N, N, N, N, H, N, N, N, N, H     1
A,H                                1
N,H                                1
H,W,H,W                            1
N,H,N                              1
Exempt                             1
Name: Ethnicity, dtype: int64
M                                  38
M, M                                9
M, M, M                             5
M,M                                 3
M, M, M, M, M                       2
M, M, F, M                          1
F                                   1
M, M, M, M, M, M, M, M, M, M, M     1
M, F                                1
M, M, M,M                           1
M,M,M,M                             1
M,M,M                               1
Exempt                              1
Name: Officer Gender, dtype: int64
28                                            4
29                                            4
33                                            4
34, 35                                        3
24                                            3
42                                            3
37                                            2
34                                            2
49                                            2
30                                            2
32                                            2
35                                            2
31                                            2
35,36,36                                      1
48,57                                         1
41, 30, 29, 33                                1
29, 32, 29, 36, 30                            1
31, 48                                        1
41, 37                                        1
28, 33, 30                                    1
29, 39, 48, 46, 34, 45, 47, 44, 47, 38, 31    1
30, 28, 28, 32                                1
34, 29                                        1
43                                            1
28, 28                                        1
25                                            1
39, 39, 27                                    1
27                                            1
31, 47, 32                                    1
36,28,30,28                                   1
36                                            1
34, 39, 47, 32, 32                            1
45,43                                         1
32, 44, 24                                    1
41                                            1
40, 28                                        1
44                                            1
26                                            1
38, 39                                        1
45,32                                         1
48                                            1
35, 34                                        1
30, 38, 37                                    1
Name: Officer Age, dtype: int64
1                                           6
4                                           5
7                                           4
8                                           4
2                                           4
9                                           3
3                                           2
5                                           2
6                                           2
14                                          1
12,12                                       1
6, 6, 5, 8, 5                               1
12, 4                                       1
15                                          1
1, 1, 1                                     1
12                                          1
11                                          1
10                                          1
4, 12                                       1
4, 5                                        1
3, 1                                        1
9, 1                                        1
6, 6                                        1
10, 5, 5                                    1
7, 11, 8, 6, 6                              1
6, 13, 4                                    1
5, 9                                        1
3, 4, 2                                     1
1,1,1,1                                     1
46,51                                       1
11,11,10                                    1
7, 18, 9                                    1
7, 25                                       1
6, 8                                        1
0.9                                         1
7, 5                                        1
6, 3, 3, 6                                  1
17.5                                        1
4, 14, 25, 23, 11, 23, 18, 21, 21, 14, 2    1
26                                          1
16,0.5                                      1
11, 5, 0.25, 4                              1
Name: Officer Tenure, dtype: int64
1    61
2     4
Name: Number of Suspects Involved, dtype: int64
Unknown                      3
Baker, Brian                 1
Davis, Albert                1
Provost, Eric                1
Roach, Kody                  1
                            ..
Rodgers, Jermassioun         1
Stephens, Antonio            1
Forster, Armani Rashaud      1
Burch, Dravious Lavon Sr.    1
Washington,William           1
Name: Suspect Name, Length: 63, dtype: int64
Black           40
White           19
Black, Black     3
Unk              1
White, White     1
Other            1
Name: Suspect Race, dtype: int64
M       57
M, M     4
F        3
Unk      1
Name: Suspect Gender, dtype: int64
27        7
23        5
22        4
17        4
25        3
32        3
34        3
Unk       2
24        2
35        2
21        2
28        2
41        2
19        2
20        2
29        2
40, 32    1
18        1
16        1
unk       1
31        1
30        1
63        1
33        1
36        1
37        1
38        1
43        1
37, 19    1
51        1
24, 24    1
57        1
21, 21    1
49        1
Name: Suspect Age, dtype: int64
Handgun                  34
Motor Vehicle            15
Hands/reaching            3
Knife                     2
No                        2
Baseball Bat              1
Motor Vehicle,Handgun     1
Handgun (2)               1
Handgun, None             1
Firearm                   1
Rifle                     1
Hands/ASP                 1
Handgun (BB)              1
Shotgun,Handgun           1
Name: Suspect's Weapon, dtype: int64
Yes             49
No              10
Yes, Yes         2
Yes, No          1
No, No           1
Unknown          1
Undetermined     1
Name: Suspect Hit, dtype: int64
No                39
Yes               20
No, No             2
Self-Inflicted     1
N                  1
Yes, No            1
No, Yes            1
Name: Fatal, dtype: int64
No                                            43
No, No                                         9
No, No, No                                     5
No, No, No, No                                 3
Yes                                            2
No, No, No, No, No                             1
Yes, No, No, No, No, No, No, No,No, No, No     1
N0                                             1
Name: Officer Hit, dtype: int64
No                                            45
No, No                                         9
No, No, No                                     5
No, No, No, No                                 2
No, No, No, NO                                 1
No, No, No, No, No, No, No, No, No, No, No     1
No, No, No, No, No                             1
Yes                                            1
Name: Fatal (Officer), dtype: int64
http://www1.cityoforlando.net/opendatadocs/saoletters/12-074536.pdf      1
http://www1.cityoforlando.net/opendatadocs/saoletters/2016-041504.pdf    1
https://www1.cityoforlando.net/opendatadocs/saoletters/18-373194.pdf     1
https://www1.cityoforlando.net/opendatadocs/saoletters/18-219116.pdf     1
http://www1.cityoforlando.net/opendatadocs/saoletters/11-521034.pdf      1
                                                                        ..
https://www1.cityoforlando.net/opendatadocs/saoletters/16-242039.pdf     1
http://www1.cityoforlando.net/opendatadocs/saoletters/14-206741.pdf      1
http://www1.cityoforlando.net/opendatadocs/saoletters/2016-153523.pdf    1
http://www1.cityoforlando.net/opendatadocs/saoletters/13-301648.pdf      1
http://www1.cityoforlando.net/opendatadocs/saoletters/18-82955.pdf       1
Name: Review Letter, Length: 59, dtype: int64
POINT (-81.37903 28.540971)              1
POINT (-81.391883 28.537072)             1
POINT (-81.417419 28.503524)             1
POINT (-81.359193 28.547668)             1
POINT (-81.378219 28.524969)             1
POINT (-81.306245 28.518123)             1
POINT (-81.45884000000001 28.496323)     1
POINT (-81.429884 28.606986)             1
POINT (-81.269617 28.420435000000005)    1
POINT (-81.477926 28.517878)             1
POINT (-81.439146 28.498257)             1
POINT (-81.379024 28.541814)             1
POINT (-81.38689 28.54016)               1
POINT (-81.334416 28.513367000000002)    1
POINT (-81.45407200000001 28.596366)     1
POINT (-81.42439700000001 28.516976)     1
POINT (-81.379591 28.540335000000002)    1
POINT (-81.436614 28.599434)             1
POINT (-81.397107 28.534377)             1
POINT (-81.389423 28.544778)             1
POINT (-81.300095 28.467533)             1
POINT (-81.416474 28.576524)             1
POINT (-81.437908 28.577163)             1
POINT (-81.335158 28.522821)             1
POINT (-81.365165 28.450897)             1
POINT (-81.457264 28.462282)             1
POINT (-81.388975 28.538149)             1
POINT (-81.244894 28.43085)              1
POINT (-81.427889 28.559822)             1
POINT (-81.346674 28.553351)             1
POINT (-81.45043 28.54529)               1
POINT (-81.318465 28.506129000000005)    1
POINT (-81.351856 28.538682)             1
POINT (-81.41360800000001 28.547812)     1
POINT (-81.349622 28.553149)             1
POINT (-81.398583 28.551919)             1
POINT (-81.41758 28.552662)              1
POINT (-81.41403 28.493798)              1
POINT (-81.419675 28.569824)             1
POINT (-81.442612 28.499375)             1
POINT (-81.307911 28.529055)             1
POINT (-81.409498 28.601495)             1
POINT (-81.379108 28.547063)             1
POINT (-81.383039 28.538425)             1
POINT (-81.435635 28.536654000000002)    1
POINT (-81.333522 28.556196)             1
POINT (-81.40856 28.552757)              1
POINT (-81.376362 28.519553)             1
POINT (-81.408405 28.512557)             1
POINT (-81.443051 28.427478)             1
Name: Georeferenced Column, dtype: int64

In [88]:
orlando['officers_white'] = get_specific_type(orlando, 'Officer Race', 'W', seperating_value=', ')
orlando['officers_black'] = get_specific_type(orlando, 'Officer Race', 'B', seperating_value=', ')
orlando['officers_other'] = get_specific_type(orlando, 'Officer Race', 'O', seperating_value=', ')
orlando['officers_race_exempt'] = get_specific_type(orlando, 'Officer Race', 'Exempt', seperating_value=', ')
orlando['officers_male'] = get_specific_type(orlando, 'Officer Gender', 'M', seperating_value=', ')
orlando['officers_female'] = get_specific_type(orlando, 'Officer Gender', 'F', seperating_value=', ')
orlando['officers_sex_unknown'] = get_specific_type(orlando, 'Officer Gender', 'Unknown', seperating_value=', ')
orlando['officers_injured'] = get_specific_type(orlando, 'Officer Hit', 'Yes', seperating_value=', ')
orlando['officers_killed'] = get_specific_type(orlando, 'Fatal (Officer)', 'Yes', seperating_value=', ')

In [89]:
orlando['suspects_white'] = get_specific_type(orlando, 'Suspect Race', 'White', seperating_value=', ')
orlando['suspects_black'] = get_specific_type(orlando, 'Suspect Race', 'Black', seperating_value=', ')
orlando['suspects_other'] = get_specific_type(orlando, 'Suspect Race', 'Other', seperating_value=', ')
orlando['suspects_race_unknown'] = get_specific_type(orlando, 'Suspect Race', 'Unknown', seperating_value=', ')
orlando['suspects_male'] = get_specific_type(orlando, 'Suspect Gender', 'M', seperating_value=', ')
orlando['suspects_female'] = get_specific_type(orlando, 'Suspect Gender', 'F', seperating_value=', ')
orlando['suspects_sex_unknown'] = get_specific_type(orlando, 'Suspect Gender', 'Unknown', seperating_value=', ')
orlando['suspects_injured'] = get_specific_type(orlando, 'Suspect Hit', 'Yes', seperating_value=', ')
orlando['suspects_killed'] = get_specific_type(orlando, 'Fatal', 'Yes', seperating_value=', ')

In [90]:
orlandoEncoded = orlando.copy()

## Sparks Nevada

In [91]:
sparks = dictOfDfs['Sparks Nevada'].copy()
sparks.info()
sparks.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   City                         19 non-null     object
 1   State                        19 non-null     object
 2   YEAR                         19 non-null     int64
 3   Type of Incident             19 non-null     object
 4   Investigating Agency Case #  19 non-null     object
 5   Action Taken Against Oficer  19 non-null     object
 6   Subject Age                  19 non-null     object
 7   Subject Gender               19 non-null     object
 8   Subject Race                 19 non-null     object
 9   Subject Armed                19 non-null     object
 10  Subject Weapon               19 non-null     object
 11  #  of SPD Officers           19 non-null     object
 12  Officer's Race               19 non-null     object
 13  Subject Struck               19 non-null     object
 14  Injuries                     19 non-null     object
dtypes: int64(1), object(14)
memory usage: 2.4+ KB

,City,State,YEAR,Type of Incident,Investigating Agency Case #,Action Taken Against Oficer,Subject Age,Subject Gender,Subject Race,Subject Armed,Subject Weapon,# of SPD Officers,Officer's Race,Subject Struck,Injuries
0,Sparks,Nevada,2000,Wanted Subject,RPD 00-236154,BDW,46,M,W,Yes,Handgun,1,White,Yes,Non Fatal
1,Sparks,Nevada,2002,Wanted Subject,RPD 02-2220,ADW,29,M,W,Unknown,Vehicle,1,White,Unknown,Non Fatal
2,Sparks,Nevada,2003,Traffic Stop,SPD 03-12116,BDW,16,M,H,No,Vehicle,1,White,No,None
3,Sparks,Nevada,2003,Wanted Subject,RPD 03-47722,ADW,23,M,W,No,Vehicle,1,White,Yes,Fatal
4,Sparks,Nevada,2005,Eluding/Warrant,SPD 05-14577,ADW,36,M,W,No,Vehicle,1,White,No,None

## Portland Oregon

In [92]:
portland = dictOfDfs['Portland Oregon'].copy()
portland.info()
portland.drop(columns = [ 
    'Internal Affairs Investigation Link',
    'Internal Affairs Investigation Link 2 (as needed)',
    'Online PDF Link',
    'Was Subject Percieved as Armed?',
    'Deadly Force Type',
    'Grand Jury Transcripts link'
])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 27 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   City                                               55 non-null     object
 1   State                                              55 non-null     object
 2   Any Officer Fatal Injuries?                        55 non-null     object
 3   Any Officers Injured on Case?                      55 non-null     object
 4   Case #                                             55 non-null     object
 5   Day of Date Time                                   55 non-null     datetime64[ns]
 6   Deadly Force Type                                  55 non-null     object
 7   Did Subject Fire Shots at Officers?                55 non-null     object
 8   General Location                                   55 non-null     object
 9   Grand Jury Transcripts link                        55 non-null     object
 10  Initial Call Type                                  55 non-null     object
 11  Internal Affairs Investigation Link                55 non-null     object
 12  Internal Affairs Investigation Link 2 (as needed)  55 non-null     object
 13  Officer Race                                       55 non-null     object
 14  Officer Sex                                        55 non-null     object
 15  Online PDF Link                                    54 non-null     object
 16  Subject Name                                       55 non-null     object
 17  Subject Race                                       55 non-null     object
 18  Subject Sex                                        55 non-null     object
 19  Subject Weapon Type (NIBRS)                        55 non-null     object
 20  Was Subject Actually Armed?                        55 non-null     object
 21  Was Subject Injured?                               55 non-null     object
 22  Was Subject Injury Fatal?                          55 non-null     object
 23  Was Subject Percieved as Armed?                    55 non-null     object
 24  Number of Officers Injured on Case                 55 non-null     int64
 25  Officer Tenure (yrs)                               55 non-null     int64
 26  Subject Age                                        55 non-null     int64
dtypes: datetime64[ns](1), int64(3), object(23)
memory usage: 11.7+ KB

,City,State,Any Officer Fatal Injuries?,Any Officers Injured on Case?,Case #,Day of Date Time,Did Subject Fire Shots at Officers?,General Location,Initial Call Type,Officer Race,Officer Sex,Subject Name,Subject Race,Subject Sex,Subject Weapon Type (NIBRS),Was Subject Actually Armed?,Was Subject Injured?,Was Subject Injury Fatal?,Number of Officers Injured on Case,Officer Tenure (yrs),Subject Age
0,Portland,Oregon,0,No,pending release (6),2020-06-28,pending release,7900 block of Southeast 6th Ave,Premise Check,Male,Male,"Stockton, Gray Tristan",White,Male,pending release,pending release,No,No,0,7,25
1,Portland,Oregon,No,No,8352-10-01 00:00:00,2010-01-29,No,Sandy Terrace Apartments,Disorder,White,Male,"Campbell, Aaron",Black,Male,None,No,Yes,Yes,0,8,25
2,Portland,Oregon,No,No,10-23336,2010-03-22,No,Hoyt Arboretum,Disorder,White,Male,"Collins, Jack",White,Male,Knife /Cutting Instrument,Yes,Yes,Yes,0,13,58
3,Portland,Oregon,No,No,10-097006,2010-11-23,Yes,11000 block SE 106th & Cherry Blossom Ave,Shots Fired,White,Male,"Boehler, Craig",White,Male,Handgun,Yes,Yes,Yes,0,17,46
4,Portland,Oregon,No,No,10-103413,2010-12-17,No,12110 East Burnside St,Disorder,White,Male,"Ferguson, Darryel Dwayne",White,Male,Firearm-replica,Yes,Yes,Yes,0,8,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,Portland,Oregon,No,Yes,11-18048,2011-03-06,Yes,3300 block Southeast 10th Ave,Behaviorial Health,White,Male,"Turner, Ralph",White,Male,Rifle,Yes,No,No,3,9,61
51,Portland,Oregon,No,Yes,14-20245,2014-03-12,Yes,SW Cheltenham St,Traffic Stop,Hispanic,Male,"Swoboda, Kelly Vern",White,Male,Handgun,Yes,Yes,Yes,1,8,49
52,Portland,Oregon,No,Yes,14-30864,2014-04-16,Yes,SW Lobelia St and Capitol Hwy,Disorder,White,Male,"Ropp, Paul",White,Male,Rifle,Yes,Yes,No,2,25,40
53,Portland,Oregon,No,Yes,15-225588,2015-07-05,No,11036 NE Sandy Blvd,Person Contact,White,Male,"Ellis, David James",White,Male,Knife /Cutting Instrument,Yes,Yes,No,1,4,55
54,Portland,Oregon,No,Yes,pending release (3),2018-10-19,pending release,Johnson Creek Fred Meyer,Traffic Stop,White,Male,"Hansen, Jason Leo",White,Male,pending release,pending release,Yes,No,1,9,29

In [93]:
for x in portland.columns:
    print(portland[x].value_counts())

Portland    55
Name: City, dtype: int64
Oregon    55
Name: State, dtype: int64
No    54
0      1
Name: Any Officer Fatal Injuries?, dtype: int64
No     48
Yes     7
Name: Any Officers Injured on Case?, dtype: int64
11-18048                                   2
19-138195                                  2
15-216504                                  2
11-375                                     2
13-018128                                  2
17-165086                                  2
19-420530                                  1
Gresham PD case                            1
10-103413                                  1
12-85653                                   1
pending release (6)                        1
1968-11-01 00:00:00                        1
14-47574                                   1
18-114856                                  1
15-225588                                  1
17-143978                                  1
Washington County Sheriff's Office case    1
16-164536                                  1
10-38353                                   1
7018-12-01 00:00:00                        1
pending release (3)                        1
18-36585                                   1
11-054666                                  1
10-105949                                  1
17-284477                                  1
15-162206                                  1
19-191223                                  1
19-258996                                  1
15-22632                                   1
12-25598                                   1
18-334543                                  1
18-681478                                  1
10-097006                                  1
13-13674                                   1
16-389389                                  1
8352-10-01 00:00:00                        1
14-20245                                   1
19-6556                                    1
pending release (4)                        1
15-385104                                  1
12-65478                                   1
17-40263                                   1
10-23336                                   1
12-62040                                   1
14-30864                                   1
pending release (5)                        1
17-39972                                   1
17-352454                                  1
14-71376                                   1
Name: Case #, dtype: int64
2017-05-28    2
2011-03-06    2
2019-04-29    2
2011-01-02    2
2015-06-28    2
2017-02-09    2
2013-03-04    2
2011-06-30    1
2010-03-22    1
2010-12-27    1
2018-10-10    1
2014-06-12    1
2014-04-16    1
2015-05-17    1
2017-10-25    1
2015-02-17    1
2019-06-09    1
2013-02-17    1
2011-01-01    1
2012-08-21    1
2017-05-10    1
2020-06-28    1
2019-12-08    1
2016-12-05    1
2010-01-29    1
2014-09-01    1
2012-07-28    1
2012-03-26    1
2019-07-30    1
2018-04-07    1
2019-01-02    1
2014-03-12    1
2017-08-30    1
2018-10-19    1
2015-03-22    1
2010-12-17    1
2018-09-30    1
2016-05-24    1
2012-01-25    1
2012-07-17    1
2018-12-07    1
2015-11-06    1
2010-05-12    1
2018-03-08    1
2012-09-29    1
2019-01-06    1
2010-11-23    1
2015-07-05    1
Name: Day of Date Time, dtype: int64
Firearm    55
Name: Deadly Force Type, dtype: int64
No                 38
Yes                14
pending release     2
Undisclosed         1
Name: Did Subject Fire Shots at Officers?, dtype: int64
Northeast 7th Ave and Lloyd Blvd               2
1950 NE 122nd Ave                              2
82nd & Powell                                  2
13136 Southeast Center St                      2
East Burnside St & Cesar E. Chavez Blvd        2
3300 block Southeast 10th Ave                  2
1500 block SE Boise Street                     1
Cityteam Ministries Portland Shelter           1
11036 NE Sandy Blvd                            1
9600 block of SE Market St                     1
915 Southwest 2nd Ave                          1
Aloha, OR                                      1
Hoyt Arboretum                                 1
3500 block SW Dakota St                        1
3037 Southwest 2nd Ave                         1
141 Northeast 147th Ave                        1
3300 block SE 22nd Ave                         1
SE 103rd Ave & SE Stark St                     1
NE 55th Ave & East Burnside St                 1
NE 6th Ave & Halsey                            1
SW Lobelia St and Capitol Hwy                  1
800 block SW King Ave                          1
SW 11th Ave & SW Highland Dr, Gresham, OR      1
12110 East Burnside St                         1
148th and NE San Rafael                        1
SW 3rd Ave & SW Harvey Milk St                 1
Good Samaritan Hospital                        1
Southeast 37th Ave between Stark and Oak St    1
SW Cheltenham St                               1
8300 block NE Hancock St                       1
Portland Adventist Medical Center              1
North Oatman Ave & Saratoga St                 1
Del Rancho Motel 7622 SE 82nd Ave              1
SE 130th Ave and SE Sherman St                 1
9000 NE Martin Luther King Jr. Blvd            1
11200 block NE Fremont St                      1
11000 block SE 106th & Cherry Blossom Ave      1
Southwest 4th & Morrison                       1
MAX bridge over Johnson Creek                  1
SE 148th Ave & East Burnside St                1
7900 block of Southeast 6th Ave                1
153rd & Southeast Division St                  1
1200 Southeast Ash St                          1
Springwater Corridor, South of Foster Rd       1
1331 Northwest Lovejoy Street                  1
Sandy Terrace Apartments                       1
3030 Northeast Weidler St                      1
Johnson Creek Fred Meyer                       1
Columbia and North Fessenden                   1
Name: General Location, dtype: int64
unavailable                                             16
No grand jury                                            8
https://www.portlandoregon.gov/police/article/541357     2
https://www.portlandoregon.gov/police/article/537829     2
https://www.portlandoregon.gov/police/article/733824     2
https://www.portlandoregon.gov/police/article/731336     1
https://www.portlandoregon.gov/police/article/740098     1
https://www.portlandoregon.gov/police/article/633835     1
https://www.portlandoregon.gov/police/article/538325     1
https://www.portlandoregon.gov/police/article/537245     1
https://www.portlandoregon.gov/police/article/536844     1
https://www.portlandoregon.gov/police/article/648735     1
https://www.portlandoregon.gov/police/article/537938     1
https://www.portlandoregon.gov/police/article/754311     1
https://www.portlandoregon.gov/police/article/537861     1
https://www.portlandoregon.gov/police/article/746513     1
https://www.portlandoregon.gov/police/article/731009     1
https://www.portlandoregon.gov/police/article/537966     1
https://www.portlandoregon.gov/police/article/532690     1
https://www.portlandoregon.gov/police/article/704329     1
https://www.portlandoregon.gov/police/article/538247     1
https://www.portlandoregon.gov/police/article/538405     1
https://www.portlandoregon.gov/police/article/538236     1
https://www.portlandoregon.gov/police/article/538343     1
https://www.portlandoregon.gov/police/article/700950     1
https://www.portlandoregon.gov/police/article/559877     1
https://www.portlandoregon.gov/police/article/637902     1
https://www.portlandoregon.gov/police/article/631011     1
https://www.portlandoregon.gov/police/article/537735     1
pending release                                          1
Name: Grand Jury Transcripts link, dtype: int64
Disorder                     15
Behaviorial Health            6
Person Contact                5
Traffic Stop                  4
Agency Assist / Warrant       3
Robbery                       3
Disturbance - Priority        3
Shots Fired                   3
Stabbing                      2
Burglary                      2
Stolen Vehicle                1
Assault - Priority            1
Premise Check                 1
Assault                       1
Trimet                        1
Suspicious - Priority         1
Unwanted Person               1
Shooting                      1
Disturbance - With Weapon     1
Name: Initial Call Type, dtype: int64
unavailable                                                                    30
pending release                                                                 4
https://www.portlandoregon.gov/police/article/734018                            2
https://www.portlandoregon.gov/police/article/744440                            1
https://www.portlandoregon.gov/police/article/500228                            1
https://www.portlandoregon.gov/police/article/714859                            1
https://www.portlandoregon.gov/police/article/532689                            1
https://www.portlandoregon.gov/police/article/740095                            1
https://www.portlandoregon.gov/police/article/732331                            1
https://www.portlandoregon.gov/police/docs/17-39972.pdf                         1
https://www.portlandoregon.gov/police/article/752749                            1
https://www.portlandoregon.gov/police/article/537860                            1
https://www.portlandoregon.gov/police/docs/18-114856.pdf                        1
https://www.portlandoregon.gov/police/article/701703                            1
https://www.portlandoregon.gov/police/images/10-8352/IA_report_Campbell.pdf     1
https://www.portlandoregon.gov/police/article/500224                            1
https://www.portlandoregon.gov/police/article/753613                            1
https://www.portlandoregon.gov/police/article/671291                            1
https://www.portlandoregon.gov/police/article/538341                            1
https://www.portlandoregon.gov/police/article/627320                            1
https://www.portlandoregon.gov/police/article/500226                            1
https://www.portlandoregon.gov/police/article/538851                            1
Name: Internal Affairs Investigation Link, dtype: int64
not applicable                                          53
https://www.portlandoregon.gov/police/article/538342     1
https://www.portlandoregon.gov/police/article/752415     1
Name: Internal Affairs Investigation Link 2 (as needed), dtype: int64
White          48
Undisclosed     2
Hispanic        2
Asian           1
Male            1
Black           1
Name: Officer Race, dtype: int64
Male      51
Female     4
Name: Officer Sex, dtype: int64
https://www.portlandoregon.gov/police/article/538365    2
https://www.portlandoregon.gov/police/article/537811    2
https://www.portlandoregon.gov/police/article/733824    2
https://www.portlandoregon.gov/police/article/645689    2
https://www.portlandoregon.gov/police/article/537968    2
https://www.portlandoregon.gov/police/article/538102    2
https://www.portlandoregon.gov/police/article/666383    1
https://www.portlandoregon.gov/police/article/537939    1
https://www.portlandoregon.gov/police/article/709065    1
https://www.portlandoregon.gov/police/article/537956    1
https://www.portlandoregon.gov/police/article/537756    1
https://www.portlandoregon.gov/police/article/740098    1
https://www.portlandoregon.gov/police/article/537108    1
https://www.portlandoregon.gov/police/article/530219    1
https://www.portlandoregon.gov/police/article/536842    1
https://www.portlandoregon.gov/police/article/537236    1
https://www.portlandoregon.gov/police/article/659461    1
https://www.portlandoregon.gov/police/article/709056    1
https://www.portlandoregon.gov/police/article/538235    1
https://www.portlandoregon.gov/police/article/576106    1
https://www.portlandoregon.gov/police/article/538355    1
https://www.portlandoregon.gov/police/article/538375    1
https://www.portlandoregon.gov/police/article/626067    1
https://www.portlandoregon.gov/police/article/751950    1
https://www.portlandoregon.gov/police/article/537889    1
https://www.portlandoregon.gov/police/article/620019    1
https://www.portlandoregon.gov/police/article/537734    1
https://www.portlandoregon.gov/police/article/645694    1
https://www.portlandoregon.gov/police/article/705235    1
https://www.portlandoregon.gov/police/article/632914    1
https://www.portlandoregon.gov/police/article/538346    1
https://www.portlandoregon.gov/police/article/537246    1
https://www.portlandoregon.gov/police/article/537919    1
https://www.portlandoregon.gov/police/article/537969    1
https://www.portlandoregon.gov/police/article/679710    1
https://www.portlandoregon.gov/police/article/538466    1
https://www.portlandoregon.gov/police/article/537858    1
https://www.portlandoregon.gov/police/article/656970    1
https://www.portlandoregon.gov/police/article/679708    1
https://www.portlandoregon.gov/police/article/538326    1
https://www.portlandoregon.gov/police/article/705408    1
https://www.portlandoregon.gov/police/article/659519    1
https://www.portlandoregon.gov/police/article/744450    1
https://www.portlandoregon.gov/police/article/538250    1
https://www.portlandoregon.gov/police/article/633061    1
https://www.portlandoregon.gov/police/article/701715    1
https://www.portlandoregon.gov/police/article/538242    1
https://www.portlandoregon.gov/police/article/709062    1
Name: Online PDF Link, dtype: int64
Cisneros III, Santiago A.       2
Higginbotham, Thomas Manford    2
Turner, Ralph                   2
Grubbe, Michael Irvin           2
Bellew, Alan Lee                2
Brock, Jeb Colin                2
Downs, David Wayne              1
Potter, Jonah Aaron             1
Bucher, Timothy James           1
Blackmon, Juwan                 1
Hansen, Jason Leo               1
Johnson, Terrell Kyreem         1
Campbell, Aaron                 1
Monroe, William                 1
Otis, Keaton                    1
Beisley, Ryan Joseph            1
Liffel, Steven Wayne            1
Tate, Jr., Michael Anthony      1
Collins, Jack                   1
Stockton, Gray Tristan          1
Rice, Samuel E.                 1
Ropp, Paul                      1
Morgan, Brad Lee                1
Sudlow, Ryan Matthew            1
McClendon, Denorris Laron       1
Brown, Sarah Michelle           1
Ferguson, Darryel Dwayne        1
Boehler, Craig                  1
Davis, Nicholas Glendon         1
Healy, Christopher Ryan         1
Peeples, Chase Arane            1
Ellis, David James              1
Kimmons, Patrick                1
Martin, Lane Christopher        1
Lagozzino, Marcus               1
Baker, Joshua Stephen           1
Hatch, Merle Mikal              1
Elifritz, John Andrew           1
Johnson, Michael Gregory        1
Simms, Billy Wayne              1
Brockner, Jesse Lee             1
Harrison, Michael Shawn         1
Gladen, Andre C.                1
Perkins, Don                    1
Moffett, Kevin Charles          1
Henriksen, Koben S.             1
Swoboda, Kelly Vern             1
Hayes, Quanice Derrick          1
Ruiz, Anita M.                  1
Name: Subject Name, dtype: int64
White       43
Black       10
Hispanic     2
Name: Subject Race, dtype: int64
Male      53
Female     2
Name: Subject Sex, dtype: int64
Knife /Cutting Instrument    18
Firearm-replica              11
Handgun                       9
Rifle                         6
None                          5
Shotgun                       2
pending release               2
Blunt Object                  1
Undisclosed                   1
Name: Subject Weapon Type (NIBRS), dtype: int64
Yes                47
No                  5
pending release     2
Undisclosed         1
Name: Was Subject Actually Armed?, dtype: int64
Yes    45
No     10
Name: Was Subject Injured?, dtype: int64
Yes    30
No     25
Name: Was Subject Injury Fatal?, dtype: int64
Yes                52
Undisclosed         1
pending release     1
No                  1
Name: Was Subject Percieved as Armed?, dtype: int64
0    48
3     3
1     3
2     1
Name: Number of Officers Injured on Case, dtype: int64
8     5
10    4
4     4
6     4
7     4
15    3
24    3
22    3
17    3
2     2
9     2
1     2
18    2
19    2
37    2
68    1
13    1
12    1
11    1
16    1
25    1
32    1
3     1
44    1
49    1
Name: Officer Tenure (yrs), dtype: int64
25     4
31     4
42     3
29     3
32     2
17     2
61     2
34     2
36     2
102    2
67     2
51     2
52     2
54     2
46     1
23     1
136    1
75     1
240    1
38     1
124    1
18     1
20     1
150    1
58     1
24     1
47     1
90     1
27     1
55     1
30     1
49     1
112    1
40     1
126    1
Name: Subject Age, dtype: int64

In [94]:
officersSubjectsCat = pd.get_dummies(portland[['Officer Race', 
                                               'Officer Sex', 
                                               'Subject Race', 
                                               'Subject Sex', 
                                               'Was Subject Injured?', 
                                               'Was Subject Injury Fatal?']])
officersSubjectsCat = pd.concat([portland['Case #'],officersSubjectsCat], axis = 1)
officersSubjectsCat = officersSubjectsCat.groupby(officersSubjectsCat['Case #']).sum().reset_index()
portlandEncoded = pd.merge(portland.groupby('Case #').first().reset_index(), officersSubjectsCat, how = 'left', on = 'Case #')

portlandEncoded.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49 entries, 0 to 48
Data columns (total 44 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Case #                                             49 non-null     object
 1   City                                               49 non-null     object
 2   State                                              49 non-null     object
 3   Any Officer Fatal Injuries?                        49 non-null     object
 4   Any Officers Injured on Case?                      49 non-null     object
 5   Day of Date Time                                   49 non-null     datetime64[ns]
 6   Deadly Force Type                                  49 non-null     object
 7   Did Subject Fire Shots at Officers?                49 non-null     object
 8   General Location                                   49 non-null     object
 9   Grand Jury Transcripts link                        49 non-null     object
 10  Initial Call Type                                  49 non-null     object
 11  Internal Affairs Investigation Link                49 non-null     object
 12  Internal Affairs Investigation Link 2 (as needed)  49 non-null     object
 13  Officer Race                                       49 non-null     object
 14  Officer Sex                                        49 non-null     object
 15  Online PDF Link                                    48 non-null     object
 16  Subject Name                                       49 non-null     object
 17  Subject Race                                       49 non-null     object
 18  Subject Sex                                        49 non-null     object
 19  Subject Weapon Type (NIBRS)                        49 non-null     object
 20  Was Subject Actually Armed?                        49 non-null     object
 21  Was Subject Injured?                               49 non-null     object
 22  Was Subject Injury Fatal?                          49 non-null     object
 23  Was Subject Percieved as Armed?                    49 non-null     object
 24  Number of Officers Injured on Case                 49 non-null     int64
 25  Officer Tenure (yrs)                               49 non-null     int64
 26  Subject Age                                        49 non-null     int64
 27  Officer Race_Asian                                 49 non-null     uint8
 28  Officer Race_Black                                 49 non-null     uint8
 29  Officer Race_Hispanic                              49 non-null     uint8
 30  Officer Race_Male                                  49 non-null     uint8
 31  Officer Race_Undisclosed                           49 non-null     uint8
 32  Officer Race_White                                 49 non-null     uint8
 33  Officer Sex_Female                                 49 non-null     uint8
 34  Officer Sex_Male                                   49 non-null     uint8
 35  Subject Race_Black                                 49 non-null     uint8
 36  Subject Race_Hispanic                              49 non-null     uint8
 37  Subject Race_White                                 49 non-null     uint8
 38  Subject Sex_Female                                 49 non-null     uint8
 39  Subject Sex_Male                                   49 non-null     uint8
 40  Was Subject Injured?_No                            49 non-null     uint8
 41  Was Subject Injured?_Yes                           49 non-null     uint8
 42  Was Subject Injury Fatal?_No                       49 non-null     uint8
 43  Was Subject Injury Fatal?_Yes                      49 non-null     uint8
dtypes: datetime64[ns](1), int64(3), object(23), uint8(17)
memory usage: 11.5+ KB

## Louisville Kentucky

In [95]:
louisville = dictOfDfs['Louisville Kentucky'].copy()
louisville.info()
louisville.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   #                        82 non-null     object
 1   Incident #               85 non-null     object
 2   Month                    66 non-null     object
 3   Day                      65 non-null     object
 4   Time of Occurrence       65 non-null     object
 5   Address of incident      65 non-null     object
 6   Division                 65 non-null     object
 7   Beat                     43 non-null     float64
 8   Investigation Type       66 non-null     object
 9   Case Status              67 non-null     object
 10  suspect_Name             69 non-null     object
 11  suspect_race             95 non-null     object
 12  suspect_sex              95 non-null     object
 13  suspect_age              66 non-null     object
 14  suspect_ethnicity        59 non-null     object
 15  suspect_weapon           68 non-null     object
 16  officer_name             93 non-null     object
 17  officer_race             95 non-null     object
 18  officer_sex              95 non-null     object
 19  officer_age              94 non-null     object
 20  officer_ethnicity        75 non-null     object
 21  officer_year_of_service  93 non-null     object
 22  Lethal Y/N               82 non-null     object
 23  Narrative                71 non-null     object
dtypes: float64(1), object(23)
memory usage: 17.9+ KB

,#,Incident #,Month,Day,Time of Occurrence,Address of incident,Division,Beat,Investigation Type,Case Status,suspect_Name,suspect_race,suspect_sex,suspect_age,suspect_ethnicity,suspect_weapon,officer_name,officer_race,officer_sex,officer_age,officer_ethnicity,officer_year_of_service,Lethal Y/N,Narrative
0,20-019,80-20-017048,March,13,0043,3003 Springfield Dr.,3,NaN,OIS,Open,Kenneth Walker III,B,M,27,U,Firearm,"Jon Mattingly,Brett Hankison,Myles Cosgrove",W,M,47,U,19,Y,Officers attempted to make entry into the resi...
1,20-020,80-20-017278,March,13,2117,8015 Blake Ln,3,NaN,OIS,Open,Justin Riggs,W,M,30,U,U,"Nathaniel Lovewell,Joseph Borst,Rebecca Davis",W,M,31,U,6,Y,Officers responded to a reported domestic viol...
2,20-024,80-20-019370,March,25,1630,3030 Talisman Road,6,NaN,OIS,Open,Byron Johnson,B,M,31,U,Firearm,"Brian Evanoff,Chad Stewart,Michael Woodard",W,M,40,U,9,N,Officers attempted to take wanted felony suspe...
3,20-026,80-20-020215,March,30,1206,200 Block E. Grey Street,1,NaN,OIS,Open,Jessie Stringfield,W,M,44,U,Firearm,Michael Johnson,W,M,41,U,11,Y,Suspect was a known fugitve with outstanding b...
4,20-030,80-20-023475,April,17,1631,2700 Block S. 7th Street,4,NaN,OIS,Open,Kendrick Holloway,B,M,42,U,Firearm,Joseph Tapp,W,M,48,U,12,N,As part of an on-going narcotics investigation...

In [96]:
for x in louisville.columns:
    print(louisville[x].value_counts())

14-090    4
11-080    4
14-043    3
17-007    2
13-051    2
         ..
19-025    1
18-066    1
12-033    1
19-012    1
19-021    1
Name: #, Length: 67, dtype: int64
Continued       20
80-20-023475     1
80-12-104103     1
8012104102       1
80-20-019370     1
                ..
80-19-028008     1
80-20-017278     1
80-14-101100     1
80-19-035697     1
80-19-059529     1
Name: Incident #, Length: 66, dtype: int64
April         12
August        10
March         10
October        7
May            5
July           5
February       4
June           3
December       3
January        2
November       2
September      2
September      1
Name: Month, dtype: int64
13       5
8        4
1        4
5        3
28       3
15       2
17       2
28th     2
23       2
25       2
20       2
21       2
31       2
13th     2
20th     2
26th     2
14       2
7        1
19th     1
8th      1
10       1
3        1
11       1
12       1
9th      1
16       1
18       1
19       1
6        1
24       1
29       1
30       1
24th     1
18       1
20       1
15th     1
27th     1
7th      1
6th      1
Name: Day, dtype: int64
2018        2
2047        1
0130am      1
2:12pm      1
04:40:00    1
           ..
2121        1
1224        1
2:50am      1
2:31am      1
18:30:00    1
Name: Time of Occurrence, Length: 64, dtype: int64
Rochelle Rd. and Smyrna Pkwy                     1
5020 Roaming Plains Ct                           1
735 Ziegler Street (Shelby Elementary School)    1
2613 W. Magazine Street                          1
1500 Rangeland                                   1
                                                ..
Rockford Ln. and Imperial Terrace                1
2902 St Xavier Street                            1
6400 Greenwood Rd.                               1
3300 Winchester Rd.                              1
Noah Dr./Cole Ave.                               1
Name: Address of incident, Length: 65, dtype: int64
3              14
1              12
6              10
2              10
4               9
7               7
8               2
Jefferstown     1
Name: Division, dtype: int64
1.0    13
3.0     9
2.0     8
5.0     6
6.0     4
4.0     3
Name: Beat, dtype: int64
OIS                                        21
SHOOTING INVESTIGATION - LMPD INVOLVED     20
DEATH INVESTIGATION-LMPD INVOLVED           8
SHOOTING INVESTIGATION-LMPD INVOLVED        6
SHOOTING INVESTIGATION- LMPD INVOLVED       3
SHOOTING INVESTIGATIONS - LMPD INVOLVED     3
DEATH INVESTIGATION - LMPD INVOLVED         2
Assault 1st-Police                          1
Wanton Endangrerment 1st                    1
Assault 1st                                 1
Name: Investigation Type, dtype: int64
CLOSED    28
Open      20
OPEN      18
Closed     1
Name: Case Status, dtype: int64
Unknown                2
Anthony French Sr      1
Norman Smith           1
Travis D. Clayton      1
Duantez A Mitchell     1
                      ..
Tracy McGraw           1
Daniel Clark           1
Jordan Monahan         1
Tayvaun Johnson        1
Benjamin J. Kennedy    1
Name: suspect_Name, Length: 68, dtype: int64
B    57
W    36
H     1
M     1
Name: suspect_race, dtype: int64
M    85
F    10
Name: suspect_sex, dtype: int64
19    6
18    5
32    4
42    3
39    3
20    3
21    3
24    3
30    3
27    2
35    2
33    2
23    2
22    2
45    2
17    2
25    1
26    1
15    1
28    1
U     1
31    1
60    1
34    1
36    1
38    1
40    1
44    1
46    1
47    1
49    1
52    1
62    1
57    1
68    1
Name: suspect_age, dtype: int64
N       21
U       20
None    17
NONE     1
Name: suspect_ethnicity, dtype: int64
Handgun          26
Firearm          15
Vehicle           7
None              4
Rifle             3
U                 2
Shotgun           2
Knife             2
Metal Rod         1
Knives            1
Knife/Saw         1
Handgun/Rifle     1
Metal Pole        1
Screwdriver       1
BB Gun            1
Name: suspect_weapon, dtype: int64
Ofc. Rondall Carpenter                            2
William Mattingly                                 2
Ofc. Bradley J. Beckham                           1
Alex Dugan/Patrick Norton                         1
Darrell Hyche                                     1
                                                 ..
Russell Braun                                     1
Nathaniel  Lovewell,Joseph Borst,Rebecca Davis    1
Sean Bell                                         1
Bryan Arnold                                      1
Ofc. Dennis Beatty                                1
Name: officer_name, Length: 91, dtype: int64
W                    78
B                    14
A                     2
W                     1
Name: officer_race, dtype: int64
M     87
F      7
M      1
Name: officer_sex, dtype: int64
26        8
27        8
24        6
31        6
30        5
28        5
41        5
23        4
25        4
35        4
36        4
32        3
42        3
29        3
44        2
39        2
34        2
40        2
45        2
47        2
56        1
37        1
33        1
55        1
38        1
Varies    1
43        1
48        1
50        1
51        1
52        1
53        1
54        1
24/29     1
Name: officer_age, dtype: int64
N       29
None    28
U       18
Name: officer_ethnicity, dtype: int64
3                15
1                11
4                10
2                 8
12                5
7                 5
11                4
9                 4
20+               4
5                 3
18                3
2 years           3
8                 3
16                2
19                2
20                2
6                 1
8yrs. 4m          1
3years            1
10                1
Under 1 year      1
Varies            1
2/3 years         1
24                1
4 years           1
Name: officer_year_of_service, dtype: int64
N            41
Y            27
Continued    13
YS            1
Name: Lethal Y/N, dtype: int64
Investigation Pending                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               10
SAA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  5
Officers attempted to take wanted felony suspect into custody at which time suspect brandished a handgun and an officer fired at the suspect.  Suspect was able to flee location and led officers on vehicle pursuit.  Officers were able to surround suspect vehilce at whihc point suspect once again brandished a handgun while exiting the vehicle at which point officers fired.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Suspect was a known fugitve with outstanding bench warrant and was spotted in the area.  Officers began canvassing the area and located the suspect.  An officer attempted to place the susepct into custody and suspect actively resisted and fought with the officer.  During the altercation the suspect pulled out a handgun from his waistband and backup officer fired at the suspect.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Officers attempted to make entry into the residence during the execution of a search warrant and were met by gunfire from within the residence.  Multiple officers returned fire.  One subject was taken into custody and another subject was killed during the incident.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
Officers responded to a reported domestic violence run and located the suspect who had fled from the location a short distance away.  The suspect refused to comply with verbal commands from officers and verbally threatened to shoot officers then made a furtive jesture jerking as his waistband at which point officers fired.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Suspect confronted officers  a weapon at officers who had arrived at residence on a domestic violence run                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
On May 17, 2012, LMPD Officers were on the scene of previous shooting when the suspect, Ms. Cheetara Goldsmith, became involved in a verbal argument with Ms. Makeba Lee.   The suspect subsequently produced a .40 caliber handgun and shot the victim several times at close range causing her death. LMPD officers ran to the area of the shooting and ordered the suspect to drop the gun.  The suspect then turned the gun in the direction of Officer Vadim Dale who fired three (3) rounds striking the suspect three (3) times.  The suspect was transported to University of Louisville Hospital, where she survived her wounds and was subsequently transferred to Louisville Metro Corrections.  The suspect was charged with the murder of Makeba Lee and Wanton Endangerment 1st Degree. Commonwealth’s Attorney David Stengel reviewed the case and found that Officer Dale’s actions were justified as self-defense as well as defense of others.     1
Officer Bryan Wilson was attempting to stop a vehicle that had fled the scene of an altercation at 35th & Broadway at a high rate of speed.  After striking a curb, the suspect vehicle came to a stop in the 3600 block of Garland Avenue.  Two (2) subjects later identified as Juvenile 1 and Juvenile 2 exited the vehicle and fired three (3) shots at Officer Wilson, who returned fire, one (1) time.  Neither the suspects, nor the officer were struck by any of the rounds.  Both suspects were arrested several days following the incident.  Juvenile 1 pled GUILTY to Attempted Murder of a Police Officer.  Juvenile 2 pled GUILTY to Wanton Endangerment 1st Degree.                                                                                                                                                                                                                                                                                  1
Officers were dispatched to incident location on a trouble run.  Upon arrival Officers entered residence when subject threw knife striking one officer in lower leg.  Officer Kaiser engaged subject when subject threw multiple knives at him, when officer fired his weapon striking subject.  Subject was transported to hospital where he succumbed to his injuries.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
Name: Narrative, Length: 58, dtype: int64

In [97]:
louisville['num_of_officers'] = [len(str(x).split(',')) for x in louisville.officer_name]
louisville.head()

,#,Incident #,Month,Day,Time of Occurrence,Address of incident,Division,Beat,Investigation Type,Case Status,suspect_Name,suspect_race,suspect_sex,suspect_age,suspect_ethnicity,suspect_weapon,officer_name,officer_race,officer_sex,officer_age,officer_ethnicity,officer_year_of_service,Lethal Y/N,Narrative,num_of_officers
0,20-019,80-20-017048,March,13,0043,3003 Springfield Dr.,3,NaN,OIS,Open,Kenneth Walker III,B,M,27,U,Firearm,"Jon Mattingly,Brett Hankison,Myles Cosgrove",W,M,47,U,19,Y,Officers attempted to make entry into the resi...,3
1,20-020,80-20-017278,March,13,2117,8015 Blake Ln,3,NaN,OIS,Open,Justin Riggs,W,M,30,U,U,"Nathaniel Lovewell,Joseph Borst,Rebecca Davis",W,M,31,U,6,Y,Officers responded to a reported domestic viol...,3
2,20-024,80-20-019370,March,25,1630,3030 Talisman Road,6,NaN,OIS,Open,Byron Johnson,B,M,31,U,Firearm,"Brian Evanoff,Chad Stewart,Michael Woodard",W,M,40,U,9,N,Officers attempted to take wanted felony suspe...,3
3,20-026,80-20-020215,March,30,1206,200 Block E. Grey Street,1,NaN,OIS,Open,Jessie Stringfield,W,M,44,U,Firearm,Michael Johnson,W,M,41,U,11,Y,Suspect was a known fugitve with outstanding b...,1
4,20-030,80-20-023475,April,17,1631,2700 Block S. 7th Street,4,NaN,OIS,Open,Kendrick Holloway,B,M,42,U,Firearm,Joseph Tapp,W,M,48,U,12,N,As part of an on-going narcotics investigation...,1

In [98]:
louisville['suspect_weapon'].value_counts()

Handgun          26
Firearm          15
Vehicle           7
None              4
Rifle             3
U                 2
Shotgun           2
Knife             2
Metal Rod         1
Knives            1
Knife/Saw         1
Handgun/Rifle     1
Metal Pole        1
Screwdriver       1
BB Gun            1
Name: suspect_weapon, dtype: int64

In [99]:
investigation_map = {
    'OIS'                                        :'Unknown',
    'SHOOTING INVESTIGATION - LMPD INVOLVED'     :'shooting',
    'DEATH INVESTIGATION-LMPD INVOLVED'          :'homicide',
    'SHOOTING INVESTIGATION-LMPD INVOLVED'       :'shooting',
    'SHOOTING INVESTIGATION- LMPD INVOLVED'      :'shooting',
    'SHOOTING INVESTIGATIONS - LMPD INVOLVED'    :'shooting',
    'DEATH INVESTIGATION - LMPD INVOLVED'        :'homicide',
    'Assault 1st-Police'                         :'assault',
    'Wanton Endangrerment 1st'                   :'reckless-endanderment',
    'Assault 1st'                                :'assault'
}

In [100]:
suspect_weapon_map = {
    'Handgun'          :'firearm',
    'Firearm'          :'firearm',
    'Vehicle'           :'other',
    'None'              :'none',
    'Rifle'             :'firearm',
    'Knife'             :'melee',
    'Shotgun'           :'firearm',
    'U'                 :'unknown',
    'Metal Rod'         :'melee',
    'Handgun/Rifle'     :'firearm',
    'BB Gun'            :'other',
    'Metal Pole'        :'melee',
    'Screwdriver'       :'melee',
    'Knife/Saw'         :'melee',
    'Knives'            :'melee'
}

In [101]:
louisville['Investigation Type'] = louisville['Investigation Type'].map(investigation_map)
louisville['suspect_weapon'] = louisville['suspect_weapon'].map(suspect_weapon_map)

In [102]:
louisvilleEncoded = louisville.copy()

## Springfiled Missouri

In [103]:
springfield = dictOfDfs['Springfiled Missouri'].copy()
springfield.info()
springfieldEncoded = springfield.drop([0,3,6,8,10,13,15,18,20,22,24,26,28]).reset_index()
springfieldEncoded

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 16 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   CASE                                                          18 non-null     object
 1   DATE                                                          18 non-null     object
 2   OFFICER: #/RACE/SEX                                           20 non-null     object
 3                                                        SUMMARY  18 non-null     object
 4   SUSPECT: RACE/GENDER                                          18 non-null     object
 5   suspect_sex                                                   18 non-null     object
 6   suspect_race                                                  18 non-null     object
 7   GREENE  COUNTY PROSECUTING DISPOSITION                        18 non-null     object
 8   number_injured                                                18 non-null     float64
 9   number_killed                                                 18 non-null     float64
 10  suspect_armed                                                 18 non-null     object
 11  incident_initiation                                           18 non-null     object
 12  num_white_officers                                            18 non-null     float64
 13  num_+pacific_island_officers                                  18 non-null     float64
 14  num_male_officers                                             18 non-null     float64
 15  num_female_officers                                           18 non-null     float64
dtypes: float64(6), object(10)
memory usage: 4.0+ KB

,index,CASE,DATE,OFFICER: #/RACE/SEX,SUMMARY,SUSPECT: RACE/GENDER,suspect_sex,suspect_race,GREENE COUNTY PROSECUTING DISPOSITION,number_injured,number_killed,suspect_armed,incident_initiation,num_white_officers,num_+pacific_island_officers,num_male_officers,num_female_officers
0,1,08-33295,7/24/2008,1 W/M,Officers responded to an assault. Suspect runs...,White/Male,male,white,Justified,0.0,1.0,melee,assault,1.0,0.0,1.0,0.0
1,2,10-05301,2/8/2010,1 W/M,Suspect of an assault was fleeing in a vehicle...,White/Male,male,white,Justified,1.0,0.0,other,assault,3.0,0.0,1.0,2.0
2,4,10-17643,5/1/2010,1 W/M,Officer stops suspected DWI driver. The rear p...,Black/Male,male,black,Justified,0.0,1.0,firearm,traffic_stop,1.0,0.0,1.0,0.0
3,5,13-7501,2/22/2013,9 W/M,Suspect burglarizes businesses and steals a ve...,White/Male,male,white,Justified,1.0,1.0,firearm,burglary,10.0,0.0,9.0,1.0
4,7,14-17329,5/9/2014,1 W/M,Officer sent to an address due to a panhandler...,White/Male,male,white,Charges Filed,1.0,0.0,none,other,1.0,0.0,1.0,0.0
5,9,14-17912,2014-05-13 00:00:00,2 W/M,Officers respond to a storage facility in rega...,White/Female,female,white,Justified,0.0,1.0,firearm,shooting,2.0,0.0,2.0,0.0
6,11,15-6228,2/17/2015,1 W/M,Officers respond to a suspected burglary. An O...,White/Male,male,white,Justified,0.0,1.0,unknown,burglary,1.0,0.0,1.0,0.0
7,12,15-44203,11/4/2015,2 W/M,Officer stops at what he believes is a traffic...,White/Male,male,white,Justified,0.0,1.0,firearm,traffic_stop,2.0,0.0,2.0,0.0
8,14,15-47472,11/25/2015,1 W/M,Officer responds to a domestic disturbance. Wh...,White/Male,male,white,Self inflicted with officer's duty weapon,0.0,1.0,melee,dv,1.0,0.0,1.0,0.0
9,16,16-07945,2016-02-27 00:00:00,1 W/M,Officer noticed a suspicious vehicle while out...,White/Male,male,white,Justified,0.0,0.0,other,suspicious_situation,2.0,0.0,1.0,0.0
10,17,17-00024,1/1/2017,3 W/M,Officers respond to a domestic disturbance inv...,Black/Male,male,black,Justified,0.0,1.0,firearm,dv,3.0,0.0,3.0,0.0
11,19,17-20253,5/11/2017,2 W/M,Officers responded to a check person with a we...,White/Male,male,white,Justified,1.0,0.0,firearm,weapon,2.0,0.0,2.0,0.0
12,21,17-35394,2017-08-12 00:00:00,1 Pacific Islander/M,Officers responded to a call where a suicidal ...,White/Male,male,white,Justified,1.0,0.0,firearm,suicide,0.0,1.0,1.0,0.0
13,23,18-00613,1/5/2018,1 W/M,Officers responded to a burglary in progress i...,White/Male,male,white,Justified,0.0,1.0,firearm,burglary,1.0,0.0,1.0,0.0
14,25,18-21518,6/4/2018,2 W/M,Officers responded to a call of a subject stea...,White/Male,male,white,Justified,0.0,1.0,firearm,theft,2.0,0.0,2.0,0.0
15,27,19-7404,2019-02-25 00:00:00,2 W/M,Officers responded to a general disturbance ca...,White/Male,male,white,Justified,1.0,1.0,melee,dv,2.0,0.0,2.0,0.0
16,29,19-13200,2019-04-09 00:00:00,1 W/M; 1 W/F,Officers were dispatched to a check the well-b...,White/Male,male,white,Justified,2.0,0.0,other,wellfare-check,2.0,0.0,1.0,1.0
17,30,19-50753,2019-12-24 00:00:00,4 W/M,Officers were dispatched to an active assault ...,White/Male,male,white,Pending,1.0,0.0,firearm,assault,4.0,0.0,4.0,0.0

In [104]:
for x in springfield.columns:
    print(springfield[x].value_counts())

19-50753     1
16-07945     1
18-00613     1
15-6228      1
10-05301     1
19-13200     1
08-33295     1
17-00024     1
17-20253     1
13-7501      1
14-17912     1
18-21518     1
19-7404      1
15-47472     1
15-44203     1
14-17329     1
10-17643     1
17-35394     1
Name: CASE, dtype: int64
 6/4/2018              1
11/25/2015             1
2014-05-13 00:00:00    1
2/22/2013              1
2016-02-27 00:00:00    1
 2/8/2010              1
2019-12-24 00:00:00    1
2019-02-25 00:00:00    1
5/11/2017              1
5/1/2010               1
1/1/2017               1
2/17/2015              1
 1/5/2018              1
5/9/2014               1
2017-08-12 00:00:00    1
11/4/2015              1
 7/24/2008             1
2019-04-09 00:00:00    1
Name: DATE, dtype: int64
1 W/M                   4
2 W/M                   3
 1 W/M                  2
1 W/M                   2
2 W/M                   1
9 W/M                   1
1 W/M; 1 W/F            1
3 W/M                   1
1 W/F                   1
 2 W/M                  1
1 Pacific Islander/M    1
4 W/M                   1
 2 W/F                  1
Name: OFFICER: #/RACE/SEX, dtype: int64
Officers were dispatched to a check the well-being call in reference to a subject passed out behind the wheel of a gray, or silver Dodge Caravan. When officers arrived, the driver of the van had revived and was driving away. Officers stopped the vehicle. During the investigation, officers learned the plates and the van were reported as stolen. Officers ordered the driver from the van, but he refused and put the vehicle in gear. One officer attempted to reach into the van to grab the keys and shut the vehicle off. That officer didn't accomplish that and the driver sped away, dragging that officer approximately 20 yards. When that officer was able to disengage from the van, the second officer fired three rounds at the driver, striking the driver once. The driver was located a short time later, ran from officers of foot, but was apprehended. The driver was taken to a local hospital and treated for his injuries. The driver was arrested for first-degree assault on a law enforcement officer.                                                                                                                                                                                                                                                                                                           1
Officers responded to a call of a subject stealing a package from the front porch of a residence. When officers arrived, several bystanders began pointing out the last location the suspect had been seen, and that the suspect was armed with a handgun. The first officer encountered the suspect on foot. The suspect immediately pulled a handgun from the front of his waistband and fired at the officer. The officer took cover behind a nearby tree and returned fire with his duty handgun, grazing the suspect with one bullet. The suspect fled, attempted to break into a residence north of the residence the shooting had occurred at. The suspect fired the gun into the residence, attempting to break into it. The suspect then ran to the west after the unsuccessful burglary. The second officer chased the suspect on foot. The second officer caught up to the suspect, who had just climbed over a six-foot chain link fence, and challenged the suspect. The suspect dropped the weapon, but within very close proximity to himself. The second officer continually gave the suspect verbal commands, but the suspect didn't comply. The suspect dropped to his knees, picked the handgun back up, and pointed it at the officer. The officer fired one round from his duty shotgun, striking and killing the suspect.    1
Suspect burglarizes businesses and steals a vehicle. Officers track suspect in snow to an address. Suspect fires a handgun at officers at the scene, striking one officer. 10 officers fire weapons at the suspect as he fires at them and attempts to flee the scene. The suspect is struck multiple times and dies as a result of gunshot wounds.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Officers responded to an assault. Suspect runs from the scene into an apartment. Suspect exits apartment with knife and approaches officer in a threatening manner. Officer discharges firearm ending the threat. Suspect dies as a result of the gunshot wound.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Officers respond to a domestic disturbance involving a firearm. Several officers arrive and locate the suspect on a bicycle. The suspect ignored verbal commands to dismount the bicycle and rode away. One officer deployed a taser, but it was ineffective. The suspect produced a handgun and a gunshot was heard by officers. Less lethal bean bags were also utilized, but were ineffective. The suspect raised the handgun towards officers and three officers fired at the suspect, ending the threat. The suspect died as a result of a gunshot wound.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
Officer stops suspected DWI driver. The rear passenger of the vehicle lies about his name and then flees on foot. The Officer chases the suspect on foot. While running the suspect produces a handgun and points it at the officer. The officer fires his weapon and ends the threat. Suspect dies as a result of gunshot wound.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
Officers responded to a check person with a weapon call. Officers located the suspect and ordered him to stop, but he fled on foot, with officers chasing him. At one point, the suspect turned and pointed a handgun at officers. Two officers fire their duty weapons ending the threat. Unknown to the officers at the time, the suspect had just robbed a convenience store in the same area. The suspect was taken into custody and survived.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Officer stops at what he believes is a traffic accident. While attempting to contact one of the drivers, the suspect flees on foot. The suspect produces a handgun and points it at his own head. After a lengthy walking pursuit, during which the suspect fires one round, the suspect then points the gun at officers. Two officers fire their weapons ending the threat. The suspect dies as a result of a gunshot wound.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
Officer sent to an address due to a panhandler. Officer contacts the suspect at the location. While speaking with the suspect, the suspect flees on foot. The officer mistakenly fires his handgun rather than his Taser, striking the suspect in the buttocks. The suspect is injured but survives. Due to the officer's actions, criminal charges were filed and the officer is terminated.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
Officers were dispatched to an active assault involving a hammer. Upon arrival, officers heard a female inside of the residence screaming for help. Officers forced entry into the residence. Officers encountered a white male armed with a handgun inside a back bedroom. As the male suspect saw officers, he racked the slide on the handgun and raised the handgun towards a female who was laying on the bed in the same room. The first officer in the "stack" fired his duty handgun four times ending the threat from the male suspect. The suspect died from his injuries.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Officers respond to a storage facility in regards to a female firing a weapon at subjects. When officers arrive the female exits an apartment and points a handgun at officers. Two officers fire their weapons and end the threat. The suspect is struck and dies as a result of a gunshot wound.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Officer noticed a suspicious vehicle while out at a convenience store. The officer contacted the driver who was uncooperative. The driver fled in the vehicle while the officer was attempting to speak to him. The officer's leg became trapped in the rear wheel well of the vehicle dragging the officer across the lot and down the street. The driver failed to stop and the officer fired 2 shots into the cab of the vehicle in an attempt to stop the driver. The officer became dislodged. The driver was not struck by the rounds.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Officers respond to a suspected burglary. An Officer becomes involved in a foot pursuit with the suspect. The suspect runs to a darkened area and begins grabbing along his waist line. Verbal commands are given by the officer to the suspect to show his hands. The suspect refuses and the officers fires his weapon ending the threat. The suspect dies as a result of a gunshot wound.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Officer responds to a domestic disturbance. When the officer arrives he contacts a female inside a home. While inside he hears a male voice in another room. The officer contacts the male who is holding a knife to his own throat. The officer gives verbal commands but the suspect fails to comply. The suspect approaches the officer with the knife and struggles with the officer over his duty weapon. During the struggle the suspect is able to pull the trigger on the officer's weapon-shooting himself The suspect dies as a result of the gunshot wound.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1

## Charolette North Carolina

In [105]:
charolette1 = dictOfDfs['Charolette North Carolina 1']
charolette2 = dictOfDfs['Charolette North Carolina offic']
charolette3 = dictOfDfs['Charolette North Carolina suspe']

In [106]:
charolette1.head()

,X,Y,INCIDENT_ID,YEAR_MONTH,LOCATION,DA_LEGAL_REVIEW,NARRATIVE,ObjectID,YR,MN,Latitude,Longitude,individual_armed,incident_initiation
0,1.447824e+06,552036.475729,7307,2008-08,"ORVIS STREET, CHARLOTTE 28216",Legally Justified,Officers served a high risk search warrant. Up...,1,2008,8,35.252694,-80.849701,firearm,warrant_service
1,1.467399e+06,553624.475134,7699,2008-11,"N TRYON STREET, CHARLOTTE 28213",Legally Justified,"Officers attempted to make a traffic stop, but...",2,2008,11,35.258041,-80.784238,firearm,traffic_stop
2,1.484298e+06,531574.479675,9687,2010-03,"E W.T. HARRIS BOULEVARD, CHARLOTTE 28227",No DA review,An officer was circulating an apartment comple...,3,2010,3,35.198285,-80.726353,firearm,burglary
3,1.479503e+06,545554.476749,10386,2010-07,"BARRINGTON DRIVE, CHARLOTTE 28278",Legally Justified,Officers observed a large crowd of individuals...,4,2010,7,35.236462,-80.743223,firearm,suspicious_situation
4,1.446813e+06,523173.481947,10392,2010-07,"PARK ROAD, CHARLOTTE 28209",Legally Justified,Officers responded to a robbery from business ...,5,2010,7,35.173350,-80.851284,firearm,robbery

In [107]:
charolette2OneHot = pd.get_dummies(charolette2[['INCIDENT_ID','OFFICER_RACE', 'OFFICER_GENDER']]).groupby('INCIDENT_ID').sum().reset_index()
charolette3OneHot = pd.get_dummies(charolette3[['INCIDENT_ID','INDIVIDUAL_RACE', 'INDIVIDUAL_GENDER', 'INDIVIDUAL_INJURY_TYPE']]).groupby('INCIDENT_ID').sum().reset_index()

In [108]:
charoletteMerge1 = pd.merge(charolette1,charolette2OneHot,on = 'INCIDENT_ID')
charoletteEncoded = pd.merge(charoletteMerge1,charolette3OneHot, on  = 'INCIDENT_ID').copy()

In [109]:
charoletteEncoded

,X,Y,INCIDENT_ID,YEAR_MONTH,LOCATION,DA_LEGAL_REVIEW,NARRATIVE,ObjectID,YR,MN,Latitude,Longitude,individual_armed,incident_initiation,OFFICER_RACE_American Indian/Alaskan Native,OFFICER_RACE_Asian or Pacific islander,OFFICER_RACE_Black,OFFICER_RACE_Hispanic,OFFICER_RACE_Undisclosed,OFFICER_RACE_White,OFFICER_GENDER_Female,OFFICER_GENDER_Male,OFFICER_GENDER_Undisclose,INDIVIDUAL_RACE_Asian or Pacific islander,INDIVIDUAL_RACE_Black,INDIVIDUAL_RACE_Hispanic,INDIVIDUAL_RACE_Unknown,INDIVIDUAL_RACE_White,INDIVIDUAL_GENDER_Female,INDIVIDUAL_GENDER_Male,INDIVIDUAL_INJURY_TYPE_Fatal Injury,INDIVIDUAL_INJURY_TYPE_Miss,INDIVIDUAL_INJURY_TYPE_Non-Fatal Injury
0,1.447824e+06,552036.475729,7307,2008-08,"ORVIS STREET, CHARLOTTE 28216",Legally Justified,Officers served a high risk search warrant. Up...,1,2008,8,35.252694,-80.849701,firearm,warrant_service,0,0,0,0,0,2,0,2,0,0,1,0,0,0,0,1,0,0,1
1,1.467399e+06,553624.475134,7699,2008-11,"N TRYON STREET, CHARLOTTE 28213",Legally Justified,"Officers attempted to make a traffic stop, but...",2,2008,11,35.258041,-80.784238,firearm,traffic_stop,0,0,1,0,0,3,0,4,0,0,1,0,0,0,0,1,0,0,1
2,1.484298e+06,531574.479675,9687,2010-03,"E W.T. HARRIS BOULEVARD, CHARLOTTE 28227",No DA review,An officer was circulating an apartment comple...,3,2010,3,35.198285,-80.726353,firearm,burglary,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0
3,1.479503e+06,545554.476749,10386,2010-07,"BARRINGTON DRIVE, CHARLOTTE 28278",Legally Justified,Officers observed a large crowd of individuals...,4,2010,7,35.236462,-80.743223,firearm,suspicious_situation,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,1
4,1.446813e+06,523173.481947,10392,2010-07,"PARK ROAD, CHARLOTTE 28209",Legally Justified,Officers responded to a robbery from business ...,5,2010,7,35.173350,-80.851284,firearm,robbery,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,1.446625e+06,558297.550629,24440,2019-03,"BEATTIES FORD ROAD, CHARLOTTE 28214",Legally Justified,"On Monday, March 25, 2019, at approximately 9 ...",79,2019,3,35.269833,-80.854107,firearm,weapon,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,1,1,0,0
79,1.454874e+06,575554.153696,25461,2019-11,"OAKBURN DRIVE, CHARLOTTE 28269",Pending Review,The State Bureau of Investigation (SBI) is con...,80,2019,11,35.317660,-80.827541,firearm,warrant_service,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,1,0,1,0
80,1.452927e+06,554755.475067,21414,2017-03,"JUSTICE AVENUE, CHARLOTTE 28206",Legally Justified,Metro division officers responded to a suicide...,81,2017,3,35.260424,-80.832779,firearm,suicide,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0,0
81,1.421752e+06,545870.092961,23428,2018-07,"WILKINSON BOULEVARD, CHARLOTTE 28208",Legally Justified,Officers with the Airport Division were dispat...,82,2018,7,35.234388,-80.936614,vehicle,suspicious_situation,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1
82,1.449903e+06,542343.153915,25521,2019-11,"E TRADE STREET, CHARLOTTE 28202",Legally Justified,The State Bureau of Investigation (SBI) is con...,83,2019,11,35.226171,-80.842135,firearm,weapon,0,0,0,0,0,2,0,2,0,0,1,0,0,0,0,1,1,0,0

In [112]:
for x in charoletteEncoded.columns:
    print(charoletteEncoded[x].value_counts())

1.480102e+06    1
1.479570e+06    1
1.444824e+06    1
1.451438e+06    1
1.452927e+06    1
               ..
1.460048e+06    1
1.455166e+06    1
1.408026e+06    1
1.449903e+06    1
1.422246e+06    1
Name: X, Length: 82, dtype: int64
541986.478048    1
562061.473776    1
520535.482588    1
541119.306741    1
558297.550629    1
                ..
566306.472312    1
541980.477510    1
545554.476749    1
533403.479333    1
526257.480946    1
Name: Y, Length: 82, dtype: int64
22525    1
1953     1
3490     1
2596     1
10789    1
        ..
9687     1
20825    1
22580    1
3932     1
20736    1
Name: INCIDENT_ID, Length: 83, dtype: int64
2016-01    3
2010-07    2
2013-09    2
2008-05    2
2016-08    2
          ..
2019-03    1
2007-10    1
2015-03    1
2016-09    1
2010-03    1
Name: YEAR_MONTH, Length: 68, dtype: int64
WILKINSON BOULEVARD, CHARLOTTE 28208    4
ALBEMARLE ROAD, CHARLOTTE 28212         3
E TRADE STREET, CHARLOTTE 28202         2
BEATTIES FORD ROAD, CHARLOTTE 28214     1
JORDANS POND LANE, CHARLOTTE 28214      1
                                       ..
N TRYON STREET, CHARLOTTE 28213         1
SNOW WHITE LANE, CHARLOTTE 28213        1
NATIONS FORD ROAD, CHARLOTTE 28273      1
N SHARON AMITY ROAD, CHARLOTTE 28205    1
BROOKSIDE DRIVE, FORT MILL 29715        1
Name: LOCATION, Length: 77, dtype: int64
Legally Justified                                      64
No DA review                                           16
Pending Review                                          2
Not Legally Justified as determined by NC AG Office     1
Name: DA_LEGAL_REVIEW, dtype: int64
Freedom Division Officers responded to an armed robbery in progress from the Cash America Pawn on Wilkinson Boulevard.  The caller stated that multiple individuals had entered the business and were robbing the business at gunpoint.  When responding officers entered the business, they encountered one of the individuals who fired a handgun at officers.  One of the officers subsequently fired his service weapon at the individual.  This individual was then immediately taken into custody.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
A CMPD K9 officer located a man who was on foot, fitting the description of a suspect wanted in two armed robberies that occurred earlier in the day.  The officer attempted to make contact with the subject in the parking lot of 1520 West Boulevard.  The officer exited his vehicle and immediately began to give loud, repeated, verbal commands to the subject.  The subject immediately began to walk quickly toward the officer, rapidly closing the distance.  The officer opened the rear door of his marked police vehicle and his K-9 exited the vehicle.  The officer gave commands to his K-9 to engage the subject.  The subject began to sprint toward the officer.  The officer continued to give loud, repeated, verbal commands to the subject; however, the subject ignored the commands and continued to rapidly advance toward the officer.  The officer fired his service weapon, striking the subject.  Crime Scene Technicians processed the scene and recovered a knife at the scene of the incident.    1
While working off-duty inside a restaurant, the officer was alerted by an employee that a subject was being assaulted by several males at the bar area of the restaurant.  The officer observed an assault between several males and the victim and ordered them to stop.  The officer then deployed his Taser on one of the males who was actively assaulting the victim.  At this time, a separate male who was an associate with the subjects involved in the assault, grabbed the officer from behind in a choke hold.  After being unable to free himself from the choke hold, the officer discharged his service weapon at the male who continued choking.                                                                                                                                                                                                                                                                                                                                                                    1
A detective with the Special Investigations Division was working in an undercover capacity and driving an unmarked unit near the intersection of Albemarle Road and Reddman Road.  The individual was not actively involved in any investigation at the time.  The driver of another vehicle collided with the detective's vehicle and began driving outbound on Albemarle Road.  The detective pulled behind the vehicle to follow it and notified Communications of the hit and run and requested assistance from a marked patrol unit.  While the detective was notifying Communications, the individual stopped his vehicle directly in front of the detective's vehicle.  The individual exited his vehicle and displayed a handgun.  The detective perceived an imminent threat and fired his service weapon, striking the individual.                                                                                                                                                                                        1
Officers from the North Tryon Division responded to an armed person call for service.  Upon arrival, officers observed an armed man outside the apartment complex.  Officers gave multiple commands to the man to drop the weapon.  The man refused to drop the weapon and the officers perceived an imminent deadly threat.  The officers subsequently fired their weapon striking the man.  The officers immediately requested Medic.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ..
Patrol officers responded to a shots fired call for service.  When officers arrived, a male inside a second story apartment exited on to his balcony and began shooting at officers, striking a patrol vehicle.  While the individual was shooting at officers, an officer returned fire.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Patrol officers responded to a domestic violence call for service involving two females.  When officers arrived on scene they were met outside the apartment by the 911 caller.  The caller stated that she and another female were involved in an argument.  Officers went inside the apartment to speak with the female who was armed with a knife. After being ordered several times to drop the knife, the female refused their commands and lunged at the officers.  One of the officers discharged his service weapon, striking the female.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
The officer responded to a residence to assist with establishing a perimeter to apprehend a possible robbery suspect.  The individual appeared between two houses and the officer gave him verbal commands to stop.  The individual ignored the commands of the officer and discharged a firearm at the officer.  The individual fired five rounds, striking the officer.  The officer returned fire.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Patrol officers responded to N. Tryon Street in reference to an armed person call for service.  The caller stated that they observed the occupants of a vehicle sitting inside the vehicle loading guns.  Officers arrived on scene and as they exited their patrol vehicles, the individuals shot at the officers.  The officers both returned fire on the individuals before the individuals fled in the vehicle.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Patrol officers responded to a 911 call for service on N. Tryon in reference to a large teen party taking place.  The caller advised that several males at the party were attempting to hide guns in their clothing.  Once officers arrived on scene, the teens began to disperse from the location.  A short time later, 911 received a call stating that shots were being fired on N. Tryon Street.  Patrol officers responded to the scene in an attempt to locate the source of the shots and to disperse the crowd.  Upon their arrival, officers observed an individual with a firearm in his possession.  Officers ordered the male to drop the weapon but he refused their commands.  An officer then discharged his service weapon, striking the male.                                                                                                                                                                                                                                                                     1
Name: NARRATIVE, Length: 83, dtype: int64
83    1
21    1
23    1
24    1
25    1
     ..
57    1
58    1
59    1
60    1
1     1
Name: ObjectID, Length: 83, dtype: int64
2016    12
2010     8
2008     8
2014     7
2019     6
2006     6
2005     6
2018     5
2017     5
2015     5
2013     5
2012     4
2011     3
2007     3
Name: YR, dtype: int64
3     11
1     10
9      9
10     8
8      7
7      7
6      7
12     6
11     6
4      5
5      4
2      3
Name: MN, dtype: int64
35.198285    1
35.226171    1
35.218810    1
35.258041    1
35.108584    1
            ..
35.253572    1
35.250254    1
35.317660    1
35.289417    1
35.234388    1
Name: Latitude, Length: 82, dtype: int64
-80.744067    1
-80.880964    1
-80.759096    1
-80.783339    1
-80.911826    1
             ..
-80.755543    1
-80.734968    1
-80.757645    1
-80.893636    1
-80.828523    1
Name: Longitude, Length: 82, dtype: int64
firearm    64
vehicle     8
melee       6
none        4
unknown     1
Name: individual_armed, dtype: int64
shooting                13
robbery                 13
traffic_stop            10
warrant_service         10
weapon                   9
suicide                  6
suspicious_situation     5
burglary                 5
dv                       5
assault                  4
homicide                 3
Name: incident_initiation, dtype: int64
0    82
1     1
Name: OFFICER_RACE_American Indian/Alaskan Native, dtype: int64
0    78
1     5
Name: OFFICER_RACE_Asian or Pacific islander, dtype: int64
0    71
1    12
Name: OFFICER_RACE_Black, dtype: int64
0    81
1     2
Name: OFFICER_RACE_Hispanic, dtype: int64
0    82
1     1
Name: OFFICER_RACE_Undisclosed, dtype: int64
1    54
0    15
2     9
3     3
8     1
7     1
Name: OFFICER_RACE_White, dtype: int64
0    76
1     7
Name: OFFICER_GENDER_Female, dtype: int64
1    59
2    11
0     7
3     3
8     1
7     1
4     1
Name: OFFICER_GENDER_Male, dtype: int64
0    82
1     1
Name: OFFICER_GENDER_Undisclose, dtype: int64
0    82
1     1
Name: INDIVIDUAL_RACE_Asian or Pacific islander, dtype: int64
1    53
0    28
3     1
2     1
Name: INDIVIDUAL_RACE_Black, dtype: int64
0    73
1    10
Name: INDIVIDUAL_RACE_Hispanic, dtype: int64
0    82
1     1
Name: INDIVIDUAL_RACE_Unknown, dtype: int64
0    67
1    16
Name: INDIVIDUAL_RACE_White, dtype: int64
0    82
1     1
Name: INDIVIDUAL_GENDER_Female, dtype: int64
1    80
3     1
2     1
0     1
Name: INDIVIDUAL_GENDER_Male, dtype: int64
0    53
1    30
Name: INDIVIDUAL_INJURY_TYPE_Fatal Injury, dtype: int64
0    65
1    17
3     1
Name: INDIVIDUAL_INJURY_TYPE_Miss, dtype: int64
0    47
1    36
Name: INDIVIDUAL_INJURY_TYPE_Non-Fatal Injury, dtype: int64

## All Cities Combined

In [158]:
pd.concat([denverEncoded, 
           la_countyEncoded,
           jacksonvilleEncoded,
           seattleEncoded,
           tacomaEncoded,
           cincinnatiEncoded,
           indianapolisEncoded,
           orlandoEncoded,
           springfieldEncoded,
           portlandEncoded,
           louisvilleEncoded,
           springfieldEncoded,
           charoletteEncoded]
         )

,id,city,state,date,time,day_of_week,call_origination,incident_initiation,address,officer_first_last,role,officer_rank,officer_badge,officer_on_duty,in_uniform,suspect_gender,suspect_age,suspect_race,suspect_ethnicity,suspect_armed,suspect_shots_fired,injury,justified,x_coord,y_coord,Corporal,Detective,Officer,Sergeant,Technician,suspect_gender_F,suspect_gender_M,suspect_race_A,suspect_race_B,suspect_race_W,suspect_ethnicity_H,suspect_ethnicity_NH,suspect_armed_firearm,suspect_armed_other,suspect_armed_unarmed,zip,district,geo_location,unit_id,unit_name,num_officers_involved,officer_race,num_of_citizens,citizen_race,num_citizens_wounded,num_citizens_killed,citizen_armed,citizen_armed_description,unit,num_white_officers,num_black_officers,num_hispanic_officers,num_filipino_officers,num_asian-pacific_officers,num_isl_officers,num_asian-pacific-isl_officers,num_unknown_officers,num_white_persons,num_black_persons,num_hispanic_persons,num_unknown_persons,id2,street_number,street_name,street_type,street_direction,apartment_number,zone,sub_zone,incident_location,officer_name,officer_sex,officer_age,officer_year_of_services,citizen_name,citizen_sex,citizen_age,citizen_injured,citizen_killed,UOFpolicy,training?,IA?,SAO,RTR,num_asian_officers,average_officer_age,average_officer_tenure,num_white_citizens,num_black_citizens,num_hispanic_citizens,num_asian_citizens,average_citizen_age,thing1,date/time,officer_year_of_service,officer_injured,num_of_rounds,citizen_DOB,citizen_weapon,on_duty,disposition,officer_disciplined,summary,officer_rank_detective,officer_rank_lieutenant,officer_rank_officer,officer_rank_sergeant,officer_rank_student_officer,officer_sex_Female,officer_sex_Male,officer_race_asian,officer_race_black,officer_race_latino,officer_race_multi-racial,officer_race_native_american,officer_race_pacific-islander,officer_race_white,officer_injured_No,officer_injured_Yes,officer_disciplined_Missing,officer_disciplined_No,officer_disciplined_Yes,citizen_sex_Female,citizen_sex_Male,citizen_race_asian,citizen_race_black,citizen_race_hispanic,citizen_race_islander,citizen_race_native_american,citizen_race_unknown,citizen_race_white,citizen_weapon_explosive,citizen_weapon_firearm,citizen_weapon_melee,citizen_weapon_other,sector,officer_years_of_service,bad_gender,corrected_citizen_gender,corrected_citizen_race,corrected_citizen_sex,officer_race_Asian,officer_race_Black,officer_race_Hispanic,officer_race_White,corrected_citizen_race_Asian,corrected_citizen_race_Black,corrected_citizen_race_Hispanic,corrected_citizen_race_Nat Am,corrected_citizen_race_Native Amer,corrected_citizen_race_White,corrected_citizen_sex_Female,corrected_citizen_sex_Male,incident_description,officer_race_BLACK,officer_race_HISPANIC/LATINO,officer_race_WHITE,officer_sex_FEMALE,officer_sex_MALE,citizen_race_ASIAN,citizen_race_BLACK,citizen_race_HISPANIC/LATINO,citizen_race_UNKNOWN,citizen_race_WHITE,citizen_sex_FEMALE,citizen_sex_MALE,citizen_sex_OTHER,division,shift,citizen_injury,officer_injury,citizent_age,City,State,Case #,Date,Address,Incident Type,Number of Officers Involved,Officer Name,Officer Race,Ethnicity,Officer Gender,Officer Age,Officer Tenure,Number of Suspects Involved,Suspect Name,Suspect Race,Suspect Gender,Suspect Age,Suspect's Weapon,Suspect Hit,Fatal,Officer Hit,Fatal (Officer),Review Letter,Georeferenced Column,officers_white,officers_black,officers_other,officers_race_exempt,officers_male,officers_female,officers_sex_unknown,officers_injured,officers_killed,suspects_white,suspects_black,suspects_other,suspects_race_unknown,suspects_male,suspects_female,suspects_sex_unknown,suspects_injured,suspects_killed,index,CASE,DATE,OFFICER: #/RACE/SEX,SUMMARY,SUSPECT: RACE/GENDER,suspect_sex,GREENE COUNTY PROSECUTING DISPOSITION,number_injured,number_killed,num_+pacific_island_officers,num_male_officers,num_female_officers,Any Officer Fatal Injuries?,Any Officers Injured on Case?,Day of Date Time,Deadly Force Type,Did Subject Fire Shots at Officers?,General Location,Grand Jury Transcripts link,Initial Call Type,Internal Affairs Investigation Link,Internal Affairs Investigation Link 2 (as needed),Officer Sex,Online PDF Link,Subject Name,Subject Race,Subject Sex,Subject Weapon Type (NIBRS),Was Subject Actually Armed?,Was Subject Injured?,Was Subject Injury Fatal?,Was Subject Percieved as Armed?,Number of Officers Injured on Case,Officer Tenure (yrs),Subject Age,Officer Race_Asian,Officer Race_Black,Officer Race_Hispanic,Officer Race_Male,Officer Race_Undisclosed,Officer Race_White,Officer Sex_Female,Officer Sex_Male,Subject Race_Black,Subject Race_Hispanic,Subject Race_White,Subject Sex_Female,Subject Sex_Male,Was Subject Injured?_No,Was Subject Injured?_Yes,Was Subject Injury Fatal?_No,Was Subject Injury Fatal?_Yes,#,Incident #,Month,Day,Time of Occurrence,Address of incident,Division,Beat,Investigation Type,Case Status,suspect_Name,suspect_weapon,officer_ethnicity,Lethal Y/N,Narrative,num_of_officers,X,Y,INCIDENT_ID,YEAR_MONTH,LOCATION,DA_LEGAL_REVIEW,NARRATIVE,ObjectID,YR,MN,Latitude,Longitude,individual_armed,OFFICER_RACE_American Indian/Alaskan Native,OFFICER_RACE_Asian or Pacific islander,OFFICER_RACE_Black,OFFICER_RACE_Hispanic,OFFICER_RACE_Undisclosed,OFFICER_RACE_White,OFFICER_GENDER_Female,OFFICER_GENDER_Male,OFFICER_GENDER_Undisclose,INDIVIDUAL_RACE_Asian or Pacific islander,INDIVIDUAL_RACE_Black,INDIVIDUAL_RACE_Hispanic,INDIVIDUAL_RACE_Unknown,INDIVIDUAL_RACE_White,INDIVIDUAL_GENDER_Female,INDIVIDUAL_GENDER_Male,INDIVIDUAL_INJURY_TYPE_Fatal Injury,INDIVIDUAL_INJURY_TYPE_Miss,INDIVIDUAL_INJURY_TYPE_Non-Fatal Injury
0,2020182,Denver,Colorado,2020-01-01,120,Wednesday,Citizen-Initiated,weapon,901 S Irving St,"Archuleta, Diego",Officer,Officer,P16061,On-Duty City Paid,Police Uniform,M,25,W,H,firearm,Yes,Not Injured,Investigation Pending,3132258,1680228,0.0,0.0,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,2.0,1.0,2.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201516702,Denver,Colorado,2015-01-09,1940,Friday,Officer-Initiated,traffic_stop,5081 N Crown Blvd,"Kindell, Sharod",Subject,Officer,P08002,On-Duty City Paid,Police Uniform,M,24,B,NH,other,Yes,Injured,http://www.denverda.org/News_Release/Decision_...,3188620,1712709,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201549266,Denver,Colorado,2015-01-26,700,Monday,Citizen-Initiated,suspicious_situation,2500 blk N Newport St / N Niagara St Alley,"Hernandez, Jessica",Subject,Officer,P05076,On-Duty City Paid,Police Uniform,F,17,W,H,other,Yes,Deceased,https://www.denverda.org/wp-content/uploads/de...,3165976,1700000,0.0,0.0,2.0,0.0,0.0,1.0,2.0,0.0,0.0,3.0,1.0,2.0,2.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201621883,Denver,Colorado,2016-01-11,1529,Monday,Officer-Initiated,traffic_stop,2601 N Zuni St,"Lonergan, Ramone",Subject,Detective,P96014,On-Duty City Paid,Plain Clothes,M,32,W,NH,firearm,Yes,Deceased,https://www.denverda.org/wp-content/uploads/de...,3135850,1700412,0.0,1.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,1.0,2.0,3.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201889020,Denver,Colorado,2018-02-06,1756,Tuesday,Citizen-Initiated,burglary,1873 S Alcott St,"Duran, Alexander",Subject,Corporal,P98027,On-Duty City Paid,Police Uniform,M,29,W,H,other,No,Deceased,https://www.denverda.org/wp-content/uploads/de...,3135881,1673982,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,1.0,1.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,NaN,NaN,NaN,NaT,NaN,NaN,NaN,weapon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.446625e+06,558297.550629,24440.0,2019-03,"BEATTIES FORD ROAD, CHARLOTTE 28214",Legally Justified,"On Monday, March 25, 2019, at approximately 9 ...",79.0,2019.0,3.0,35.269833,-80.854107,firearm,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
79,NaN,NaN,NaN,NaT,NaN,NaN,NaN,warrant_service,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.454874e+06,575554.153696,25461.0,2019-11,"OAKBURN DRIVE, CHARLOTTE 28269",Pending Review,The State Bureau of Investigation (SBI) is con...,80.0,2019.0,11.0,35.317660,-80.827541,firearm,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
80,NaN,NaN,NaN,NaT,NaN,NaN,NaN,suicide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.452927e+06,554755.475067,21414.0,2017-03,"JUSTICE AVENUE, CHARLOTTE 28206",Legally Justified,Metro division officers responded to a suicide...,81.0,2017.0,3.0,35.260424,-80.832779,firearm,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
81,NaN,NaN,NaN,NaT,NaN,NaN,NaN,suspicious_situation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.421752e+06,545870.092961,23428.0,2018-07,"WILKINSON BOULEVARD, CHARLOTTE 28208",Legally Justified,Officers with the Airport Division were dispat...,82.0,2018.0,7.0,35.234388,-80.936614,vehicle,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0